### ISSUE TITLE
How can I use parents?

### ISSUE THREAD

**Issue by ArjanQside** [yiisoft/yii2-elasticsearch#100]
Hello,

I have a question. I tried to use parents in Elasticsearch. I think I need to use "_parent" for the parent.
I can use it in the browser with this code:
`
POST /books/chapter/1?parent=1
{
    "chapter_number": "01", 
    "title": "Installation Windows 2012",
    "start_page_print" : 11,
    "start_page_hocr" : 7,
    "end_page_print" : 59,
    "end_page_hocr" : 55,
    "create_date" : "06-09-2016",
    "updated_date" : "06-09-2016",
    "created_by" : 1,
    "updated_by" : 1
}`

But know I need to insert the _parent in Yii. I tried many things, but nothings works...

How can I do that?

Regards,
Arjan

**Comment by beowulfenator** [comment]
Take a look at [`Command::insert()`](http://www.yiiframework.com/doc-2.0/yii-elasticsearch-command.html#insert()-detail). The fifth parameter is the options array. In your typical application you do something like this:

    Yii::$app->elasticsearch->createCommand()->insert('books', 'chapter', [
        "chapter_number" => "01",
        "title" => "Installation Windows 2012",
        "start_page_print" => 11,
        "start_page_hocr" => 7,
        "end_page_print" => 59,
        "end_page_hocr" => 55,
        "create_date" => "06-09-2016",
        "updated_date" => "06-09-2016",
        "created_by" => 1,
        "updated_by" => 1
    ], 1, ['parent' => 1]);
