### ISSUE TITLE
How to get the last Primary Key?

### ISSUE THREAD

**Issue by ArjanQside** [yiisoft/yii2-elasticsearch#102]
Hello guys,

I've made a CRUD for managing books, but I got this hard-coded in the beforeSave() code in the model:
`public function beforeSave($insert)
    {

        if($this->isNewRecord){
            $this->primaryKey = 10;
            $this->id = $this->primaryKey;
            $this->create_date = date("Y-m-d H:i:s");
            $this->update_date = date("Y-m-d H:i:s");
            $this->created_by = Yii::$app->user->getId();
            $this->updated_by = Yii::$app->user->getId();
        }
        else{
            $this->update_date = date("Y-m-d H:i:s");
            $this->updated_by = Yii::$app->user->getId();
        }    
        return true && parent::beforeSave($insert);
    }`

So I need to change the `$this->primaryKey = 10;` everytime to another primary key.
How can I get the last Primary Key of the last inserted record of this table?

Kind regards,
Arjan

**Comment by cebe** [comment]
1. why don't you use auto incrementing primary key column?
2. closing as this is a question.

**Comment by cebe** [comment]
if you do not specify a primary key, elasticsearch will auto generate one for you. It will not be an integer however. Is that an option that would work for your case?

**Comment by cebe** [comment]
Note that there is no way in elasticsearch to generate unique integer ids because if you have a cluster you can not ensure uniqueness without introducing a master or some locking/voting procedure.

**Comment by ArjanQside** [comment]
Well, there is no way to set a column to Auto Incrementing in Elasticsearch I think. 
I can try to add a column with ID  and make this one AI.

e.g:
I want to get easy PK's like 1, 2, 3 etc, so I can make easy a relation between Books and Chapters table.
I give the Chapters table a parent ID, which is related with PK of the Books table.

**Comment by beowulfenator** [comment]
@ArjanQside You are not using ES for its intended purpose. Implementing an autoincrement attribute in ES is NOT the solution to your problem (which, I assume, is creating a parent-child relationship for models). At this time there is no proper support for nested models in yii2-elasticsearch. Eventually we will implement it. For now, find a workaround that is suitable for you.
