### ISSUE TITLE
no hightlighth result return?

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/yii2-elasticsearch#11]
~~~php
$query = [];
        $keyword = trim($keyword);
        if ($keyword) {
            $query = [
                'multi_match' => [
                    'query' => $keyword,
                    'fields' => ['title', 'keywords', 'description', 'content']
                ]
            ];
        }

        return [
            'items' => (new Query())->from('apd', 'news')->query($query)->highlight([
                'fields' => [
                    'title' => []
                ]
            ])->all()
        ];
~~~

no hightlighth result return?

**Comment by samdark** [comment]
What do you mean?

**Comment by cebe** [comment]
highlight will be returned when you call `search()` instead of `all()`.

**Comment by hiscaler** [comment]
use search() is same as all()

**Comment by cebe** [comment]
I am using this feature in my projects so I am quite sure it works. Will add a unit test to verify it.

**Comment by hiscaler** [comment]
Tks, is work now. because json_encode encode ['title': []] to {'title': []}, but elasticsearch is require {'title': {}}

**Comment by hiscaler** [comment]
Solution is if you will use a empty object, you use ['title' => new \stdClass()], will generate {"title": {}}
