### ISSUE TITLE
can not work with elasticsearch 5.0

### ISSUE THREAD

**Issue by liyadongcn** [yiisoft/yii2-elasticsearch#112]
### What's expected?
updating elasticsearch from 2.4.1 to 5.0.0.  
### What do you get instead?
![image](https://cloud.githubusercontent.com/assets/3737160/20000398/35b07fda-a2b2-11e6-8393-ae4415e21544.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.6
| PHP version      | 5.5.12
| Operating system | windows 10

**Comment by cebe** [comment]
> https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-5.0.0.html
> 
>  Remove the scan and count search types. https://github.com/elastic/elasticsearch/pull/13310

**Comment by beowulfenator** [comment]
I think we should just specify that there is no support for ES 5 in yii2-elasticsearch for now.

**Comment by cebe** [comment]
I have added a note to there readme.

**Comment by siliconalchemy** [comment]
This is a fairly major issue, can anyone suggest workarounds for now?

**Comment by cebe** [comment]
stay on elasticsearch 4.x ;)

**Comment by siliconalchemy** [comment]
@cebe Too late, but thanks ;)

**Comment by bxcodec** [comment]
So when we will support  ES  5.x version ?

**Comment by cebe** [comment]
when someone finds the time to work on it.

**Comment by zinzinday** [comment]
@version 2.0.4 many bug with 5.x )
@see https://www.elastic.co/guide/en/elasticsearch/reference/5.x/breaking-changes-5.0.html

**Comment by beowulfenator** [comment]
For ES5 try the 2.1 branch.

**Comment by ahmadazizi** [comment]
We really appreciate all the efforts. It's almost July, meaning 9 months since this issue has opened. I hope we hear good news about supporting ES 5.X. The version 5.x has some new features that could not be ignored and use the older 4.x. Thank you.

**Comment by samdark** [comment]
@beowulfenator is 2.1 stable? If so, how about fixing the rest for 2.0 and then releasing 2.0 and 2.1?

**Comment by harman83in** [comment]
I noticed a few commits on 2.1 branch over the last 2 days. Does this mean ES 5.x support is on the horizon?

**Comment by cebe** [comment]
@harman83in I am able to use this extension on elasticsearch 5.x and tests are passing. However due to low test coverage I am unsure on how good ES 5.x support is at the moment. A good help would be to extend unit tests, or to try the 2.1 branch in your applications and report problems if you find any.

**Comment by core01** [comment]
Any news about 2.1 stability?

**Comment by cebe** [comment]
yiiframework.com is running the 2.1 branch in production https://github.com/yiisoft-contrib/yiiframework.com/blob/896d7441d1580c61c31966ab7a7b441c9e6ed039/composer.json#L21

it works for our use case, but I am not sure how stable it is in general.

**Comment by beowulfenator** [comment]
Elasticsearch 5 is now supported.
