### ISSUE TITLE
ActiveRecord and ActiveDataProvider

### ISSUE THREAD

**Issue by az-joss** [yiisoft/yii2-elasticsearch#121]
### What steps will reproduce the problem?
Elasticsearch ActiveRecord does not allow to use custom fields within ActiveDataProvider

**model declaration**
```
class SomeIndex extends \yii\elasticsearch\ActiveRecord
{
    // custom field
    private $url;

    public funciton attributes()
    {
         return [
             '_id', // it is required for working inside of ActiveDataProvider
             'name'
         ];
    }
    
    // getter for custom field
    public function getUrl()
    {
        return Url::to(['index/view', 'id' => $this->primaryKey]);
    }
}
```

**rest controller action**
(configured to return JSON)
```
public function actionTest()
{
    $query = SomeIndex::find();
        ->fields(['name', 'url']);
    
    // here base provider because \yii\elasticsearch\ActiveDataProvider
    // is not loaded through composer
    return new \yii\data\ActiveDataProvider([
        'query' => $query,
        'pagination' => [
            'pageSize' => 3
        ]
    ]);
}
```

### What's expected?
Expected that in result of collection ll be custome field `url`
e.g.
```
[
    {
        "name": "regular name",
        "url": "/index/view?id=1"
    }
    ....
]
```

### What do you get instead?
I put custom field to `attributes()` - so, it is no longer the custom field

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.10
| PHP version      | 5.6.26
| Operating system | macOS 10.12 Sierra
| yiisoft/yii2-elasticsearch version | 2.0.4

**Comment by klimov-paul** [comment]
You should setup `ActiveDataProvider::$key` to the different column, e.g. `url`.
