### ISSUE TITLE
composer update the following error

### ISSUE THREAD

**Issue by ohuangbino** [yiisoft/yii2-elasticsearch#126]
composer update the following error?

Your requirements could not be resolved to an installable set of packages.?
Problem 1
    - The requested package fancyecommerce/fecshop >=1.0.1.2 is satisfiable by fancyecommerce/fecshop[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by beowulfenator** [comment]
Surely this is not a problem with our package, but with `fancyecommerce/fecshop`.
