### ISSUE TITLE
yii2-elasticsearch 2.1: query bug

### ISSUE THREAD

**Issue by webspec2012** [yiisoft/yii2-elasticsearch#127]
Code:

```
$query = (new Query())
            ->from('place', 'main')
            ->andWhere(['location.region_id' => \Yii::$app->controller->region->id])
            ->query(['match' => ['_all' => 'Химки']]);

$dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => false,
            'pagination' => [
                'pageSize' => 12,
            ],
 ]);

$dataProvider->getModels();
```

Generated query:

```
GET place/main/_search
{"size":12,"query":{"constant_score":{"filter":{"bool":{"must":[{"term":{"location.region_id":83}}]}}}}}
```

without query match -(

**Comment by beowulfenator** [comment]
You're welcome to fix this. If you do, be sure to add this case to tests.

**Comment by chelsEg** [comment]
I also had this problem.

I was helped by this [example]( https://www.elastic.co/guide/en/elasticsearch/reference/6.4/query-filter-context.html#query-filter-context).

You need to change your code to something like this:
`$query = (new Query())
            ->from('place', 'main')
            ->query([
                'bool' => [
                    'must' => [
                        'match' => [
                            '_all' => 'Химки'
                        ]
                    ],
                    'filter' => [
                        'term' => [
                            'location.region_id' => \Yii::$app->controller->region->id
                        ]
                    ]
                ]
            ]);
`

**Comment by beowulfenator** [comment]
Duplicate of #171. Both `query()` and `andWhere()` overwrite the internal `$query` attribute. Whichever is called last applies.
