### ISSUE TITLE
Elasticsearch request failed: 7 - Failed to connect to localhost port 9200: Connection refused

### ISSUE THREAD

**Issue by LuisY93** [yiisoft/yii2-elasticsearch#129]
### What steps will reproduce the problem?
How resolve this problem:
Elasticsearch request failed: 7 - Failed to connect to localhost port 9200: Connection refused
### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.11
| PHP version      | 7.0.9
| Operating system | Windows

**Comment by beowulfenator** [comment]
I am sorry, but are you sure you have an ElasticSearch server running at `localhost:9200`? It is very unlikely that this problem has to do with the library itself.

**Comment by LuisY93** [comment]
Yes my configuration is:

'elasticsearch' => [
            'class' => 'yii\elasticsearch\Connection',
            'nodes' => [
                ['http_address' => '127.0.0.1:9200'],

                // configure more hosts if you have a cluster
            ],
        ],

How enable port 9200?

**Comment by beowulfenator** [comment]
Your issue has to do with your own server configuration, not the library.

**Comment by xiaoxiaoqing1** [comment]
最后怎么解决的

**Comment by samdark** [comment]
Make sure ElasticSearch is running on a port that is specified in the config.
