### ISSUE TITLE
Infinite query loop "ActiveDataProvider" when the index does not exist

### ISSUE THREAD

**Issue by unasoft** [yiisoft/yii2-elasticsearch#134]
### What steps will reproduce the problem?
When the index does not exist and we refer to it, we get false because the expected array is trying to get data again and so infinitely
```php
    public function getQueryResults()
    {
        if (!is_array($this->_queryResults)) {
            $this->prepare();
        }
        return $this->_queryResults;
    }
 ``` 

PS: Sorry for my english

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | n/a
| PHP version      | n/a
| Operating system | n/a

**Comment by eolitich** [comment]
code exemple:
```
$provider = new ActiveDataProvider([
      'query' => Entry::find(),
      'pagination' => [
      'pageSize' => 10,
  ]
]);

return $this->render('index', ['models' => $provider->getModels()]);
```
if the index doesn't exist, the page hangs up because "getQueryResult" expects array but `$results = $query->search($this->db);` false returns and prepare in a cycle is launched
```
   public function getQueryResults()
    {
        if (!is_array($this->_queryResults)) {
            $this->prepare();
        }
        return $this->_queryResults;
    }
```
