### ISSUE TITLE
Connection::httpRequest() doesn't proccess errors received in response body

### ISSUE THREAD

**Issue by sizeg** [yiisoft/yii2-elasticsearch#136]
I'm using ES 5.2 and it returns error on post request in this manner:

> 
> 200 OK
> 
> content-type: application/json; charset=UTF-8
> 
> {"took":0,"errors":true,"items":[{"create":{"_index":"music","_type":"album","_id":"42760","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse [artistTags]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:134"}}}}]}
> 

Should `\yii\elasticsearch\Connection::httpRequest()` interpretates it as error and throw exception? Or we should manualy parse such kind of errors?

**Comment by cebe** [comment]
why does it return a HTTP 200 code in case of an error? I would consider that a bug in elasticsearch.

**Comment by sizeg** [comment]
@cebe seems that it's ok for bulk commands. I found this discussions: 
https://github.com/elastic/elasticsearch/issues/25156
https://github.com/elastic/elasticsearch/issues/18978

Shortly, each bulk can have own errors.

**Comment by beowulfenator** [comment]
This is not a bug. As noted above, there are two cases when Elasticsearch's code 200 response is questionable. In case of partial shard failures, I would not consider it an error. After all, we do get a result.

As for partial failures of batch requests, that is what they are, a batch. Every item in a batch can succeed or fail and it can fail in its own way. This should be described in the docs, hence the "docs" label.

**Comment by beowulfenator** [comment]
Reflected these considerations in the docs.
