### ISSUE TITLE
Cluster autodetection did not find any active nodes.

### ISSUE THREAD

**Issue by dungphanxuan** [yiisoft/yii2-elasticsearch#137]
I connnect with amazone ElasticSearch so has error

![image](https://user-images.githubusercontent.com/10725732/27982123-f6424a0c-63c4-11e7-8dc6-5f0ded30fd5e.png)

What wrong or i missing some config.

**Comment by dungphanxuan** [comment]
I see command, that has problem with AWS

**Comment by cebe** [comment]
can you provide your elasticsearch component configuration?

**Comment by dungphanxuan** [comment]
This is ElasticSearch for test, i set access policy is publish.
http://search-awaw-kfwqddlnvbxuatzysdpcq5fuua.us-west-2.es.amazonaws.com

My config
```php
 'elasticsearch' => [
            'class' => 'yii\elasticsearch\Connection',
            //'autodetectCluster' => false,
            'nodes' => [
                ['http_address' => 'search-awaw-kfwqddlnvbxuatzysdpcq5fuua.us-west-2.es.amazonaws.com']         
            ],
        ],
```

**Comment by cebe** [comment]
Thanks, I have checked the result returned from the node and it does not contain the information that should be contained by default. According to the elasticsearch docs, a request to `/_nodes` should return a `http_address` field for each host, that is not the case in your setup...

https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html

**Comment by cebe** [comment]
I have improved the error message and updated the docs. Thanks for reporting!

**Comment by gertmedia24** [comment]
I am also getting this issue. Using ES 6.2, and latest yii2 advanced app (as of June 2018).
@cebe I'm not seeing a http_address being returned as default here (maybe it's been updated?):
https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html

**Comment by githubjeka** [comment]
Yes
5.4 contain http_address
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/cluster-nodes-info.html#cluster-nodes-info

5.5 not
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/cluster-nodes-info.html#cluster-nodes-info
