### ISSUE TITLE
ActiveDataProvider class not exists in releases.

### ISSUE THREAD

**Issue by momone83** [yiisoft/yii2-elasticsearch#138]
I have added yii2-elasticsearch (v2.0.4) through composer but ActiveDataProvider class is absent.

The class exists in the repository but not in the releases.

![schermata 2017-07-26 alle 16 21 18](https://user-images.githubusercontent.com/6953666/28626228-b791c680-721e-11e7-8589-a5a5423ab6a0.png)

Thanks.

| Q                | A
| ---------------- | ---
| Yii version       |2.0.9
| PHP version      |5.6.30
| Operating system |macOS Sierra

**Comment by beowulfenator** [comment]
You're right, `ActiveDataProvider` is not a part of any stable release (yet). Use `#dev-master`.
