### ISSUE TITLE
Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header

### ISSUE THREAD

**Issue by momone83** [yiisoft/yii2-elasticsearch#139]
"httpRequest" method of Connection class returns the following error.

**299 Elasticsearch-5.5.0-260387d \"Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.**

Infact the CURLOPT_HTTPHEADER option of curl request (line 377 of Connection class) appears as follow:

**CURLOPT_HTTPHEADER     => ['Expect:']**

The Content-Type option is not specified.

| Q                | A
| ---------------- | ---
| Yii version      |2.0.9 
| PHP version      |5.6.30
| Operating system |macOS Sierra

**Comment by beowulfenator** [comment]
Elasticsearch 5 is only supported in the experimental 2.1 branch. Try using that one.

**Comment by momone83** [comment]
I added yiisoft/yii2-elasticsearch form 2.1 branch but nothing is changed.
I have the same error.

**Comment by cebe** [comment]
fixed by #143
