### ISSUE TITLE
elastic IP address problem

### ISSUE THREAD

**Issue by liyadongcn** [yiisoft/yii2-elasticsearch#140]
### What steps will reproduce the problem?
elasticsearch can not get the right ip address of the local machine in case. Actually i always get the problem recently.
![image](https://user-images.githubusercontent.com/3737160/28699441-3e960d5e-737c-11e7-98c2-546855c80e55.png)

![image](https://user-images.githubusercontent.com/3737160/28699426-28042350-737c-11e7-8667-160bddb16465.png)

 

### What do you get instead?
i have to restart the elasticsearch service in my windows.

### Additional info

in the config file the setting is 127.0.0.1:9200

| Q                | A
| ---------------- | ---
| Yii vesion      2.0.6 |
| PHP version    5.5.6  |
| Operating system windows 10 |

**Comment by samdark** [comment]
That's not something we can affect from within Yii, right?

**Comment by cebe** [comment]
> That's not something we can affect from within Yii, right?

Yes, this is how elasticsearch advertises itself using a wrong IP address. Had this issue when switching networks with my laptop. Got a new IP but elasticsearch did not detect that, you need to restart elasticsearch in that case. If you still have problems, you can disable cluster autodetection.
