### ISSUE TITLE
PHP 7.2 support?

### ISSUE THREAD

**Issue by fijas** [yiisoft/yii2-elasticsearch#149]
### What steps will reproduce the problem?
Update to PHP 7.2 and try out the extension.

### What's expected?
The extension should work normally.

### What do you get instead?
file: "/var/www/genesis/server/vendor/yiisoft/yii2/base/Object.php"
line: 28
message: "Cannot use 'Object' as class name as it is reserved"
name: "PHP Compile Error"
stack-trace: [,…]
0: "#0 /var/www/genesis/server/vendor/yiisoft/yii2-elasticsearch/QueryBuilder.php(20):::spl_autoload_call()"

### Additional info
`Object` has been made a reserved keyword from PHP 7.2 onwards

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13.1
| PHP version      | 7.2
| Operating system | Arch Linux

**Comment by schmunk42** [comment]
Related https://github.com/yiisoft/yii2-gii/issues/318
