### ISSUE TITLE
Add Suggestions from _search endpoint to ActiveDataProvider

### ISSUE THREAD

**Issue by lawli3t** [yiisoft/yii2-elasticsearch#156]
Since Elasticsearch 5.0.0 the _suggest endpoint is deprecated. Add the possibility to fetch suggestions the non-deprecated way to ActiveDataProvider in a similar manner as aggregations.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html

**Comment by beowulfenator** [comment]
Fixed by #281
