### ISSUE TITLE
resetIndex() in ActiveFixture don't clear index

### ISSUE THREAD

**Issue by sashsvamir** [yiisoft/yii2-elasticsearch#157]
I'm try to add fixtures to es 2.3.4 index.
Fixtures was added successfuly, but there no reset index before. Everytime as i run tests, fixtures has append to index.
When resetIndex() in ActiveFixture class executes, runtime going to Connection class to line 508:
`$responseCode = curl_getinfo($this->_curl, CURLINFO_HTTP_CODE); `
where $responseCode is becoming 404, on attached screenshot you can see a little more debug information.

Now i'm having:
yii2 2.0.13.1
and last #2ed2451 of yii2-elasticsearch

![screen shot 2018-01-12 at 22 49 29](https://user-images.githubusercontent.com/1404421/34893143-0b610dbc-f7ed-11e7-9844-ba7b15d80505.png)

**Comment by sashsvamir** [comment]
I'm found solution, problem was appears here:
```
$ curl -XDELETE http://localhost:9200/shop-test/product/_query -d '{"query":{"match_all":{}}}'
{"found":false ....[skipped]
```
after installing es plugin **delete-by-query** issue was resolved:
```
$ curl -XDELETE http://localhost:9200/shop-test/product/_query -d '{"query":{"match_all":{}}}'
{"took":0,"timed_out":false,"_indices":{"_all":{"found":19,"deleted":19... [skipped]
```

It seems like _delete by query_ not available since v2.0.
Can't find information about required this plugin on this extension. May be add this info to README.md?

more about **delete-by-query** plugin here: [https://www.elastic.co/guide/en/elasticsearch/plugins/2.3/plugins-delete-by-query.html](url)

**Comment by samdark** [comment]
Yes. Won't hurt.

**Comment by yurii-github** [comment]
just faced this problem with ES6

you can do like this

```
    protected function resetIndex()
    {
        $result = $this->db->post(
            [$this->index, $this->type, '_delete_by_query'],
            [],
            json_encode(['query' => ['match_all' => new \stdClass()]]));
}
```

**Comment by sashsvamir** [comment]
Yes, **_query** was depricated from es 5.0.
And at [branch 2.1](https://github.com/yiisoft/yii2-elasticsearch/tree/2.1) i'm offer suggestion #159 to use **_delete_by_query** instead, but still no response.
