### ISSUE TITLE
Missing some files in distribution zipballs

### ISSUE THREAD

**Issue by deltacube** [yiisoft/yii2-elasticsearch#160]
Hi there,
I'm trying to download the latest release (2.0.4) with composer that has been done. But some files from repo are missing, such as:
 - ActiveDataProvider.php
 - BatchQueryResult.php
 - BulkCommand.php
 - ElasticsearchTarget.php

To reproduce this issue, in empty folder perform this command:
`php composer.phar require --prefer-dist yiisoft/yii2-elasticsearch`

`composer show yiisoft/yii2-elasticsearch`
That appoints the zipball which is actually do not contain this files:
[https://api.github.com/repos/yiisoft/yii2-elasticsearch/zipball/c752e9ef2eb0bf6807f6b3a4fadc885f6f7fef59](https://api.github.com/repos/yiisoft/yii2-elasticsearch/zipball/c752e9ef2eb0bf6807f6b3a4fadc885f6f7fef59)

With another releases the same problem

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13.1
| PHP version      | PHP 7.0.27-1~dotdeb+8.1
| Operating system | Linux Debian 8 jessie amd64

**Comment by beowulfenator** [comment]
Revision 2.0.4 doesn't have those files. These features are in master branch, not released yet.
