### ISSUE TITLE
message: "Cannot use 'Object' as class name as it is reserved"

### ISSUE THREAD

**Issue by sashsvamir** [yiisoft/yii2-elasticsearch#161]
Using php 7.2 lead to error: `message: "Cannot use 'Object' as class name as it is reserved"`

### Additional info
| Q                | A
| ---------------- | ---
| Yii vesion       2.0.12|
| PHP version      7.2|

**Comment by RSalo** [comment]
since 2.0.13, the class name `Object` is invalid since PHP 7.2, use [[BaseObject]] instead.

**Comment by harekrishnarastogi** [comment]
Go to **vendor->yiisoft** folder and replace the latest yii library yiisoft. It is working fine for me.

**Comment by logudotcom** [comment]
> Go to **vendor->yiisoft** folder and replace the latest yii library yiisoft. It is working fine for me.

It worked
