### ISSUE TITLE
How to use Facets Filter

### ISSUE THREAD

**Issue by stonely2012** [yiisoft/yii2-elasticsearch#17]
I use Facets with addAggregation as below
$query->addAggregation('category', 'terms', ['field' => 'category_id']);

Now, I only want facets with category with parent category id = 30. How to filter it?

**Comment by klimov-paul** [comment]
@stonely2012, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
