### ISSUE TITLE
No search type for [count]

### ISSUE THREAD

**Issue by CZhen** [yiisoft/yii2-elasticsearch#175]
### What steps will reproduce the problem?
$query->count()
### What's expected?
search result  total 
### What do you get instead?
Class query line 376
    public function count($q = '*', $db = null)
    {
        // TODO consider sending to _count api instead of _search for performance
        // only when no facety are registerted.
        // http://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html
        // http://www.elastic.co/guide/en/elasticsearch/reference/1.x/_search_requests.html

        $options = [];
        //$options['search_type'] = 'count';

        return $this->createCommand($db)->search($options)['hits']['total'];
    }
### Additional info

| Q                | A
| ---------------- | ---
| Yii version       |   Yii 2
| PHP version      |   PHP 5.6.32
| Operating system |  Mac os

**Comment by cebe** [comment]
I assume you are using an incompatible version of elasticsearch? which version of the extension are you using and which version of elasticsearch itself?

See https://github.com/yiisoft/yii2-elasticsearch#requirements

**Comment by AnticDroid** [comment]
"yiisoft/yii2-elasticsearch": "~2.1"
 "yiisoft/yii2": "~2.0.14",

**Comment by takeaki** [comment]
This should be implemented
