### ISSUE TITLE
scroll() call is failing with a long scroll_id

### ISSUE THREAD

**Issue by russianlagman** [yiisoft/yii2-elasticsearch#176]
### What steps will reproduce the problem?
Just have many shards and use the scroll api.

### What's expected?
Normal BatchQueryResult operation.

### What do you get instead?
Something like:
`
Error Info:
Array
(
    [requestMethod] => GET
    [requestUrl] => http://localhost:9200/_search/scroll?scroll_id=c2NhbjsxMzA7MTI1NDYzODM6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjM4MTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2MzgyOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDYzODQ6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjM4NTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2Mzg2OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDYzODc6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjM5MTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2Mzg4OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDYzOTI6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjM5MDpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2Mzg5OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDYzOTM6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjM5NDpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2Mzk1OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDYzOTY6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjM5NzpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2Mzk4OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDYzOTk6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQwMDpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDAxOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0MDI6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQwMzpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDA0OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0MDU6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQwNjpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDA3OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0MDg6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQwOTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDEwOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0MTE6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQxMjpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDEzOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0MTQ6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQxNTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDE2OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0MTc6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQxODpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDE5OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0MjA6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQyMTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDIyOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0MjM6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQyNDpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDI1OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0MjY6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQyNzpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDI4OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0Mjk6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQzMDpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDMxOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0MzI6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQzMzpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDM0OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0MzU6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQzNjpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDM3OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0Mzg6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQzOTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDQwOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0NDE6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ0MjpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDQzOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0NDQ6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ0NTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDQ2OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0NDc6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ0ODpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDQ5OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0NTA6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ1MTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDUyOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0NTM6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ1NDpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDU1OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0NTY6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ1NzpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDU4OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0NTk6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ2MDpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDYxOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0NjI6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ2MzpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDY0OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0NjU6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ2NjpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDY3OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0Njg6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ2OTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDcwOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0NzE6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ3MjpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDczOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0NzQ6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ3NTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDc2OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0Nzc6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ3ODpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDc5OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0ODA6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ4MTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDgyOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0ODM6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ4NDpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDg1OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0ODY6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ4NzpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDg4OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0ODk6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ5MDpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDkxOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0OTI6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ5MzpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDk0OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0OTU6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ5NjpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NDk3OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY0OTg6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjQ5OTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NTAwOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY1MDE6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjUwMjpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NTAzOktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY1MDQ6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjUwNTpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NTA2OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY1MDc6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxMjU0NjUwODpLV2ZJZFgwelNPcXZBdlNmbVlyRURBOzEyNTQ2NTA5OktXZklkWDB6U09xdkF2U2ZtWXJFREE7MTI1NDY1MTA6S1dmSWRYMHpTT3F2QXZTZm1ZckVEQTsxO3RvdGFsX2hpdHM6MTgwMDIzMDk7&scroll=1m
    [requestBody] => 
    [responseHeaders] => Array
        (
        )

    [responseBody] => 
)
`
0% (0/155000) ETA: n/a   `
### Additional info
See https://discuss.elastic.co/t/scroll-id-is-too-long-java-api/24665
Query string can't be longer then 4096 bytes.

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.15
| PHP version      | 7.1
| Operating system | Linux

**Comment by cebe** [comment]
This sounds like a problem of elasticsearch itself. Do you have any idea whether it is possible to fix this on the library side?

**Comment by cebe** [comment]
what is the error message? also please provide the full exception with stack trace.

**Comment by russianlagman** [comment]
@cebe http URL is limited to the around 2k symbols. That's why huge scroll_id doesn't fit.
You need to change the api call from GET to POST here. And send the scroll_id as a POST parameter.

**Comment by russianlagman** [comment]
@cebe our current working scroll() implementation:

```
