### ISSUE TITLE
When yii2 supports elasticsearch 6

### ISSUE THREAD

**Issue by fancyecommerce** [yiisoft/yii2-elasticsearch#179]
When yii2 supports elasticsearch 6?

Is there a plan for the yii2 project team?

**Comment by fancyecommerce** [comment]
Whenyii2-elasticsearch supports elasticsearch 6
Is there a plan for the yii2-elasticsearch project team?

**Comment by samdark** [comment]
When it's implemented. There's no fixed deadline. If you need it bad you can implement it and submit a pull request.
