### ISSUE TITLE
Implementation of with()

### ISSUE THREAD

**Issue by AnatolyRugalev** [yiisoft/yii2-elasticsearch#18]
I implemented support of with() for hasOne relations and I need your voice for it.

First thing is to allow `$model->_id` usage. It need for `ActiveQuery::getModelKey()` method. It cannot find any value in _id property and sets `NULL` key for each found record. Fixed with:

File: ActiveRecord

``` php
    public function __get($name)
    {
        if ($name == '_id') {
            return parent::__get('primaryKey');
        } else {
            return parent::__get($name);
        }
    }

    public function __set($name, $value)
    {
        if ($name == '_id') {
            parent::__set('primaryKey', $value);
        } else {
            parent::__set($name, $value);
        }
    }

    public function __isset($name)
    {
        if ($name == '_id') {
            return parent::__isset('primaryKey');
        } else {
            return parent::__isset($name);
        }
    }

    public function __unset($name)
    {
        if ($name == '_id') {
            parent::__unset('primaryKey');
        } else {
            parent::__unset($name);
        }
    }
```

Second thing is to increase size of limit when requesting `all()` in `ActiveQuery::populateRecord`. It needs because of ElasticSearch returns only 10 items if size is not set.

Fixed with:

File: ActiveQuery, line: 65

``` php
$models = $this->limit(count($primaryModels))->all();
```

With this modifications this code works as designed:

``` php
class User extends \yii\elasticsearch\ActiveRecord {
...
    public function getDbModel() {
        return $this->hasOne(\common\models\User::className(), ['_id' => 'id']);
    }
...
}

foreach(User::find()->with(['dbModel'])->all() as $elasticUser) {
    echo $user->dbModel->id . "\n";
}

```

**Comment by hutsi** [comment]
+1

**Comment by enaza** [comment]
An important point. I support the idea

**Comment by HUNTERxp** [comment]
+1

**Comment by Singularity303** [comment]
+1

**Comment by TiniTun** [comment]
Yes, +1

**Comment by cebe** [comment]
this should currently work:

```php

	/**
	 * @return \yii\elasticsearch\ActiveQuery
	 */
	public function getProject()
	{
		return $this->hasOne(Project::className(), ['_id' => 'projectId']);
	}
```

**Comment by AnatolyRugalev** [comment]
@cebe It works when lazy load is performing, but with greedy one - no. I had array of null values as result.

```php
$posts = ElasticPost::find()->with(['user'])->all();
foreach ($posts as $post) {
    var_dump($post->user); // NULL
}
```

**Comment by beowulfenator** [comment]
@AnatolyRugalev, I am trying to replicate this error without success. I am using models from tests ([`Order`](https://github.com/yiisoft/yii2-elasticsearch/blob/d5f9c6cf68b207caef79093b17137fba63c4d7b5/tests/data/ar/Order.php) and [`Customer`](https://github.com/yiisoft/yii2-elasticsearch/blob/d5f9c6cf68b207caef79093b17137fba63c4d7b5/tests/data/ar/Customer.php)), and this code seems to work:
```
$models = Order::find()->with(['customer'])->asArray()->all();
foreach ($models as $model) {
    var_dump($model);
}
```

In the var_dump I see the `customer` attribute is populated. I've tried eager-loading other attributes (e.g. `orderItems`), and that also works.

Can you confirm your observation?

**Comment by beowulfenator** [comment]
Could not reproduce.

**Comment by AnatolyRugalev** [comment]
@beowulfenator Sorry I could not elaborate this issue because it happened more than a five years ago  :smile: 

Thanks for checking this out though!

Good luck
