### ISSUE TITLE
PHP7.2 warning in count(), fatal exception in YII

### ISSUE THREAD

**Issue by nailfor** [yiisoft/yii2-elasticsearch#180]
### What steps will reproduce the problem?
esSearch::find()->where(['id'=>[1,2]])->All();

### What's expected?
count

### What do you get instead?
count(): Parameter must be an array or an object that implements Countable
QueryBuilder.php, function buildInCondition(317 line)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.6
| PHP version      | 7.2
| Operating system | linux

After php7.2 the count() must accept an array or object
   if (is_array($column) && count($column) > 1) {

   }

**Comment by cebe** [comment]
fixed, thanks for reporting!
