### ISSUE TITLE
Unable to install branch 2.1 as STABLE

### ISSUE THREAD

**Issue by momone83** [yiisoft/yii2-elasticsearch#181]
How can I install branch 2.1 as stable? Composer shows me a STABLE branch but I'm not able to install it in my project. Only -dev seems to be available.

Thanks.

| Q                | A
| ---------------- | ---
| Yii version      2.0.15 |
| PHP version      5.6|
| Operating system macos|

**Comment by cebe** [comment]
2.1 is not stable yet.

**Comment by samdark** [comment]
@tonyzheng1990 does it look stable enough?

**Comment by core01** [comment]
Hi all, unable to install 2.1.x-dev as STABLE ![](https://image.prntscr.com/image/nIewAsyrRY2-7yWj4MUOlA.jpeg)

**Comment by beowulfenator** [comment]
It's not stable (yet).

**Comment by core01** [comment]
@beowulfenator ok, thank you, do you know any knowing issues with 2.1.x version? Can I use it in production?

**Comment by cebe** [comment]
yiiframework.com is running the 2.1 branch in production https://github.com/yiisoft-contrib/yiiframework.com/blob/896d7441d1580c61c31966ab7a7b441c9e6ed039/composer.json#L21

it works for our use case, but I am not sure how stable it is in general.

**Comment by schmunk42** [comment]
@samdark @cebe This one would be something for the next release day ;)

**Comment by samdark** [comment]
@schmunk42 I've spent about 4 days trying to fix travis builds already. Can not proceed without having it done. See https://github.com/yiisoft/yii2-elasticsearch/issues/232 and https://github.com/yiisoft/yii2-elasticsearch/issues/233.
