### ISSUE TITLE
I'm not able to connect with AWS Elasticsearch 6.2 Service

### ISSUE THREAD

**Issue by tarunjangra** [yiisoft/yii2-elasticsearch#184]
I'm installed with 2.1 yii2-elasticsearch version because es i'm trying to work with is 6.2. And it is not allowing me to connect with AWS elasticsearch service. Where as my custom elasticsearch installation works fine.

### What steps will reproduce the problem?
here is my component configuration. 
`'elasticsearch' => [
      'class' => 'yii\elasticsearch\Connection',
      'nodes' => [
        [
          'http_address' => 'end-point.es.amazonaws.com',
          'protocol' => 'https'
        ],
      ],
    ],`
Producing following error
`Executing...PHP Notice 'yii\base\ErrorException' with message 'Undefined index: http'

in /var/www/html/staging/vendor/yiisoft/yii2-elasticsearch/Connection.php:190

Stack trace:
#0 /var/www/html/staging/vendor/yiisoft/yii2-elasticsearch/Connection.php(190): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/html/s...', 190, Array)
#1 /var/www/html/staging/vendor/yiisoft/yii2-elasticsearch/Connection.php(155): yii\elasticsearch\Connection->populateNodes()
#2 /var/www/html/staging/vendor/yiisoft/yii2-elasticsearch/Connection.php(259): yii\elasticsearch\Connection->open()
#3 /var/www/html/staging/common/models/es/BaseModel.php(129): yii\elasticsearch\Connection->createCommand()
#4 /var/www/html/staging/common/models/es/BaseModel.php(134): common\models\es\BaseModel::deleteIndex()
#5 /var/www/html/staging/console/controllers/EsController.php(114): common\models\es\BaseModel::resetIndex()
#6 /var/www/html/staging/console/controllers/EsController.php(206): console\controllers\EsController->reindexInBulk(Array, '100')
#7 [internal function]: console\controllers\EsController->actionReindex()
#8 /var/www/html/staging/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/staging/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/staging/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('reindex', Array)
#11 /var/www/html/staging/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('reindex', Array)
#12 /var/www/html/staging/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('es/reindex', Array)
#13 /var/www/html/staging/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('es/reindex', Array)
#14 /var/www/html/staging/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 /var/www/html/staging/yii(31): yii\base\Application->run()
#16 {main}
`
### What's expected?
It should be connect. but as per connection.php. It is simply ignoring nodes where http:publish_address key is not available in the response.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.14
| PHP version      | 5.6
| Operating system | ubuntu 16.04
| yii2-elasticsearch | 2.1

**Comment by cebe** [comment]
> It is simply ignoring nodes where http:publish_address key is not available in the response.

if there is no `http:publish_address` we do not know how to connect to the node, can you show how the response looks like?

**Comment by xjoyzaza** [comment]
IN  vendor yiisoft yii2-elasticsearch change the ` foreach ($nodes as $key => &$node) {
            
            // Make sure that nodes have an 'http_address' property, which is not the case if you're using AWS
            // Elasticsearch service (at least as of Oct., 2015). - TO BE VERIFIED
            // Temporary workaround - simply ignore all invalid nodes
            if (!isset($node['http']['publish_address'])) {
                unset($nodes[$key]);
            }
            $node['http_address'] = $node['http']['publish_address'];

            //Protocol is not a standard ES node property, so we add it manually
            $node['protocol'] = $this->defaultProtocol;
        }`  
to ` foreach ($nodes as $key => &$node) {
           
            $node['http_address'] = $host;

            //Protocol is not a standard ES node property, so we add it manually
            $node['protocol'] = $this->defaultProtocol;
        }`

**Comment by cebe** [comment]
@xjoyzaza can you show me what is in $nodes at that point? That would help, me to fix this in the extension itself so you don't need that workaround.

**Comment by xjoyzaza** [comment]
> @xjoyzaza can you show me what is in $nodes at that point? That would help, me to fix this in the extension itself so you don't need that workaround.

  there is no  $node["http"] res in aws response ...

**Comment by cebe** [comment]
that is clear, but what do we have? could you show an example reponse?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-elasticsearch/pull/217/commits/e96e440bb99c2c5a3af8b2f261e5a4ebfe617a60 may fix it.

**Comment by tkijewski** [comment]
Setting autodetectCluster to false will basically use the node specified in the config. This works for me

```
'elasticSearch' => [
            'class' => 'yii\elasticsearch\Connection',
            'defaultProtocol'=>'https',
            'autodetectCluster'=>false,
            'nodes' => [
                ['http_address' => '<your-node>.us-east-1.es.amazonaws.com'],
            ],
        ],
```

**Comment by beowulfenator** [comment]
Node autodetection issue adressed in 2.0.4:
> - Enh #28: AWS Elasticsearch service compatibility (andrey-bahrachev)

If autodetection does not work, the recommended solution is to disable autodetection and list nodes manually.
