### ISSUE TITLE
How to use 'sort' with 'query' in search

### ISSUE THREAD

**Issue by gvanto** [yiisoft/yii2-elasticsearch#186]
Info: Using "yiisoft/yii2-elasticsearch": "2.1.x-dev"

I would like to do the following using yii2 elastic:
(from https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html) 

> GET /my_index/_search
> {
>     "sort" : [
>         { "post_date" : {"order" : "asc"}},
>         "user",
>         { "name" : "desc" },
>         { "age" : "desc" },
>         "_score"
>     ],
>     "query" : {
>         "term" : { "user" : "kimchy" }
>     }
> }

But there doesn't seem to be a find->sort([sort input]) method (as there is a find()->query() )?

Help appreciated,
gvanto

**Comment by tarunjangra** [comment]
No, find()->sort() is not available. Actually this question is more about knowing Yii. I've done following.
`    $provider = new ActiveDataProvider([
        'query' => $model->find()->query($query),
        'pagination' => [
          'pageSize' =>  10,
        ],
        'sort' => [
          'defaultOrder' => [
            'id' => SORT_DESC
          ],
        ]
      ]);`
So put your query in $query without sorting options.
