### ISSUE TITLE
ActiveRecord::deleteAll() delete only 10 items

### ISSUE THREAD

**Issue by ruslansp** [yiisoft/yii2-elasticsearch#19]
On good method is to completely clear the database but only removes 10 records, this is due to the fact that the default Elastic returns 10 records (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request- from-size.html)
Temporarily problem was solved: Model :: getDb () -> createCommand () -> deleteIndex (Model :: index ())

**Comment by beowulfenator** [comment]
Fixed in #51
