### ISSUE TITLE
yii2-Elasticsearch Found an error that an inherited class could not find

### ISSUE THREAD

**Issue by yaofaqian** [yiisoft/yii2-elasticsearch#196]
### What steps will reproduce the problem?
An error was found. Inheriting the BaseObject base class in QureyBuilder. PHP would report an error that could not be found. Change the class to Object and use it properly. By the way, change the BaseObjcet from use above to Object
### Additional info

| Q                | A
| ---------------- | ---
| Yii version       |2.0
| PHP version      |5.6
| Operating system |Linux
elasticsearch version 6.4.1

**Comment by samdark** [comment]
Update framework package to latest version please.
