### ISSUE TITLE
Calling unknown method: yii\elasticsearch\ActiveQuery when trying to use scope

### ISSUE THREAD

**Issue by khvalov** [yiisoft/yii2-elasticsearch#197]
Model: 
```
<?php
namespace common\models;
use yii\elasticsearch\ActiveRecord;

Class ObjectsElastic extends ActiveRecord
{
    public static function active()
    {
        $this->andWhere(['status' => 1]);
    }
```
In controller: 
`
$model=ObjectsElastic::find()->active();
`

caused error: 
Calling unknown method: yii\elasticsearch\ActiveQuery::active()

Any thoughts ?

**Comment by cebe** [comment]
You defined a method in class `ObjectsElastic` and you try to call it on the Query... that can not work.

You need to define a custom query class. 	
https://www.yiiframework.com/doc/guide/2.0/en/db-active-record#customizing-query-classes
