### ISSUE TITLE
plan for elasticSearch6 ？  2019 will coming。

### ISSUE THREAD

**Issue by fancyecommerce** [yiisoft/yii2-elasticsearch#198]
plan for elasticSearch6 ？  2019 will coming。

hope support es6 in 2019

thanks

**Comment by stafot** [comment]
@fancyecommerce 2.1.x works also with es6.

**Comment by fancyecommerce** [comment]
@stafot  this bug has fixed?  

https://github.com/yiisoft/yii2-elasticsearch/issues/167

**Comment by beowulfenator** [comment]
Good news! At work we're upgrading to ES 6.5, so now I'll have an incentive to make improvements to the 2.1 branch. So, soon.
