### ISSUE TITLE
Maximum function nesting level of '256' reached, aborting! in /vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php:82

### ISSUE THREAD

**Issue by AnticDroid** [yiisoft/yii2-elasticsearch#201]
**On "minimum-stability": stable  work fine !**

Infinite loop after Yii2 update:
    https://github.com/yiisoft/yii2/commit/a5182e5d5eecc52622d8e1a0b3c6cb43641f5ca1

### What steps will reproduce the problem?

1. php composer.phar create-project --prefer-dist yiisoft/yii2-app-basic basic
2. Set elastic componet auth data ...
3. Changes in composer.json

"minimum-stability": stable --> dev,
"php": >=5.4.0 --> >=7.0
"require": add "yiisoft/yii2-elasticsearch": "~2.1"

Finaly composer.json

```
{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Project Template",
    "keywords": ["yii2", "framework", "basic", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "dev",
    "require": {
        "php": ">=7.0",
        "yiisoft/yii2": "~2.0.14",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "yiisoft/yii2-elasticsearch": "~2.1"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1",
        "codeception/specify": "~0.4.3"
    },
    "config": {
        "process-timeout": 1800,
        "fxp-asset": {
            "enabled": false
        }
    },
    "scripts": {
        "post-install-cmd": [
            "yii\\composer\\Installer::postInstall"
        ],
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject",
            "yii\\composer\\Installer::postInstall"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ]
        },
        "yii\\composer\\Installer::postInstall": {
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}
```

4. \app\controllers\SiteController::actionIndex
```
    /**
     * Displays homepage.
     * @return string
     */
    public function actionIndex()
    {
        $query = new \yii\elasticsearch\Query();
        $query->limit(10);
        $query->from('report', 'report');

        $provider = new \yii\elasticsearch\ActiveDataProvider([
            'query'      => $query,
            'pagination' => [
                'pageSize' => 2
            ],
        ]);

        $models =  $provider->getModels();

        var_dump($models);
        die;

        return $this->render('index');
    }
```
5. php yii serve
6. curl -X GET 'http://localhost:8080'

### What's expected?
\yii\elasticsearch\ActiveDataProvide::getModels() return array

### What do you get instead?
```
[Wed Jan 16 20:17:25 2019] PHP Error:  Maximum function nesting level of '256' reached, aborting! in basic/vendor/yiisoft/yii2/base/Component.php on line 307
[Wed Jan 16 20:17:25 2019] PHP Stack trace:
[Wed Jan 16 20:17:25 2019] PHP   1. {main}() basic/web/index.php:0
[Wed Jan 16 20:17:25 2019] PHP   2. yii\web\Application->run() basic/web/index.php:12
[Wed Jan 16 20:17:25 2019] PHP   3. yii\web\Application->handleRequest() basic/vendor/yiisoft/yii2/base/Application.php:386
[Wed Jan 16 20:17:25 2019] PHP   4. yii\web\Application->runAction() basic/vendor/yiisoft/yii2/web/Application.php:103
[Wed Jan 16 20:17:25 2019] PHP   5. app\controllers\SiteController->runAction() basic/vendor/yiisoft/yii2/base/Module.php:528
[Wed Jan 16 20:17:25 2019] PHP   6. yii\base\InlineAction->runWithParams() basic/vendor/yiisoft/yii2/base/Controller.php:157
[Wed Jan 16 20:17:25 2019] PHP   7. call_user_func_array:{basic/vendor/yiisoft/yii2/base/InlineAction.php:57}() basic/vendor/yiisoft/yii2/base/InlineAction.php:57
[Wed Jan 16 20:17:25 2019] PHP   8. app\controllers\SiteController->actionIndex() basic/vendor/yiisoft/yii2/base/InlineAction.php:57
[Wed Jan 16 20:17:25 2019] PHP   9. yii\elasticsearch\ActiveDataProvider->getModels() basic/controllers/SiteController.php:74
[Wed Jan 16 20:17:25 2019] PHP  10. yii\elasticsearch\ActiveDataProvider->prepare() basic/vendor/yiisoft/yii2/data/BaseDataProvider.php:117
[Wed Jan 16 20:17:25 2019] PHP  11. yii\elasticsearch\ActiveDataProvider->prepareModels() basic/vendor/yiisoft/yii2/data/BaseDataProvider.php:104
[Wed Jan 16 20:17:25 2019] PHP  12. yii\elasticsearch\ActiveDataProvider->getPagination() basic/vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php:89
[Wed Jan 16 20:17:25 2019] PHP  13. yii\elasticsearch\ActiveDataProvider->prepareTotalCount() basic/vendor/yiisoft/yii2/data/BaseDataProvider.php:199
[Wed Jan 16 20:17:25 2019] PHP  14. yii\elasticsearch\ActiveDataProvider->getQueryResults() basic/vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php:117
[Wed Jan 16 20:17:25 2019] PHP  15. yii\elasticsearch\ActiveDataProvider->prepare() basic/vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php:50
[Wed Jan 16 20:17:25 2019] PHP  16. yii\elasticsearch\ActiveDataProvider->prepareModels() basic/vendor/yiisoft/yii2/data/BaseDataProvider.php:104
[Wed Jan 16 20:17:25 2019] PHP  17. yii\elasticsearch\ActiveDataProvider->getPagination() basic/vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php:89
[Wed Jan 16 20:17:25 2019] PHP  18. yii\elasticsearch\ActiveDataProvider->prepareTotalCount() basic/vendor/yiisoft/yii2/data/BaseDataProvider.php:199
[Wed Jan 16 20:17:25 2019] PHP  19. yii\elasticsearch\ActiveDataProvider->getQueryResults() basic/vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php:117
[Wed Jan 16 20:17:25 2019] PHP  20. yii\elasticsearch\ActiveDataProvider->prepare() basic/vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php:50
[Wed Jan 16 20:17:25 2019] PHP  21. yii\elasticsearch\ActiveDataProvider->prepareModels() basic/vendor/yiisoft/yii2/data/BaseDataProvider.php:104
...
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.16-dev
| PHP version      | 7.1.25
| Operating system | Mojave

**Comment by AnticDroid** [comment]
"yiisoft/yii2-elasticsearch": "~2.1"

**Comment by AnticDroid** [comment]
In SearchModel on call getModels method:

$query = new yii\elasticsearch\Query();
$provider = new ActiveDataProvider([
    'query' => $query,
]);
$provider->getModels();

**Comment by samdark** [comment]
What's in the query?

**Comment by AnticDroid** [comment]
> What's in the query?

{"size":50,"query":{"constant_score":{"filter":{"bool":{"must":[{"range":{"reg_date":{"gte":"2019-01-16T00:00:00+03:00"}}},{"range":{"reg_date":{"lte":"2019-01-16T23:59:59+03:00"}}}]}}}},"sort":[{"reg_date":"desc"}]}

**Comment by GHopperMSK** [comment]
I can't reproduce the problem.

```
ghopper@TM1701 ~/Projects/yii2.test ((HEAD detached at a5182e5d5)) $ uname -a
Linux farm 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
ghopper@TM1701 ~/Projects/yii2.test ((HEAD detached at a5182e5d5)) $ curl -X GET 'http://localhost:9200'
{
  "name" : "node-1",
  "cluster_name" : "elastic_cluster",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
```
SiteController.php
```
    public function actionAbout()
    {

//        for ($i = 11; $i < 60; $i++) {
//            $city = new City();
//            $city->primaryKey = $i;
//            $r = rand(5, 50);
//            $city->attributes = [
//                'message' => 'message#' . $i,
//                'reg_date' => date(\DateTime::ISO8601, strtotime(" +{$r} day"))
//            ];
//            $city->save();
//        }

        $query = City::find()
            ->where(['>', 'reg_date', date(\DateTime::ISO8601, strtotime(" +5 day"))])
            ->andWhere(['<', 'reg_date', date(\DateTime::ISO8601, strtotime(" +15 day"))])
            ->orderBy(['reg_date' => SORT_DESC])
            ->limit(10);
        $provider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [ 'pageSize' => 10 ],
        ]);
        $tmp = $provider->getModels();

        return $this->render('about', [
                'provider' => $provider,
            ]
        );
    }

```
And in `about.php` view:
```
<?= GridView::widget([
    'dataProvider' => $provider,
    'id' => 'grid-id',
    'columns' => [
        'message',
        [
            'class' => ActionColumn::className(),
            // you may configure additional properties here
        ],
    ],
]) ?>

```

Everything works fine! Pagination, total row amount, sorting and so on. Do I misunderstood something?

**Comment by AnticDroid** [comment]
Just now clear and reinstall vendor. Problem still exist for 2.0.16-dev + yiisoft/yii2-elasticsearch ~2.1
After rollback to  yii 2.015 all works.

On yii 2.016  i see trouble on https://github.com/yiisoft/yii2/commit/a5182e5d5eecc52622d8e1a0b3c6cb43641f5ca1#diff-3a9563dfdfd2448d1b7edfad3ec14522 
lines 197-203


Error: Maximum function nesting level of '256' reached, aborting! in /vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php:82
Stack trace:
#0 /vendor/yiisoft/yii2/data/BaseDataProvider.php(104): yii\elasticsearch\ActiveDataProvider->prepareModels()
#1 /vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php(50): yii\data\BaseDataProvider->prepare()

#2 /vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php(117): yii\elasticsearch\ActiveDataProvider->getQueryResults()
#3 /vendor/yiisoft/yii2/data/BaseDataProvider.php(199): yii\elasticsearch\ActiveDataProvider->prepareTotalCount()
#4 /vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php(89): yii\data\BaseDataProvider->getPagination()
#5 /vendor/yiisoft/yii2/data/BaseDataProvider.php(104): yii\elasticsearch\ActiveDataProvider->prepareModels()
#6 /vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php(50): yii\data\BaseDataProvider->prepare()

....

#242 /vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php(117): yii\elasticsearch\ActiveDataProvider->getQueryResults()
#243 /vendor/yiisoft/yii2/data/BaseDataProvider.php(199): yii\elasticsearch\ActiveDataProvider->prepareTotalCount()
#244 /vendor/yiisoft/yii2-elasticsearch/ActiveDataProvider.php(89): yii\data\BaseDataProvider->getPagination()
#245 /vendor/yiisoft/yii2/data/BaseDataProvider.php(104): yii\elasticsearch\ActiveDataProvider->prepareModels()
#246 /vendor/yiisoft/yii2/data/BaseDataProvider.php(117): yii\data\BaseDataProvider->prepare()

#247 /common/models/Server/Report/Elastic/ReportElasticSearch.php(270): yii\data\BaseDataProvider->getModels()
#248 /backend/controllers/ReportController.php(57): common\models\Server\Report\Elastic\ReportElasticSearch->search(Array)
#249 [internal function]: backend\controllers\ReportController->actionIndex()
#250 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#251 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#252 /vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('index', Array)
#253 /vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('report/index', Array)
#254 /vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#255 /backend/web/index.php(131): yii\base\Application->run()
#256 {main}

**Comment by samdark** [comment]
Aha, I think "yiisoft/yii2-elasticsearch ~2.1" matters.

**Comment by AnticDroid** [comment]
What version is right for 
{
"name": "...",
"cluster_name": "..",
"cluster_uuid": "....",
"version": {
"number": "5.6.2",
"build_hash": "57e20f3",
"build_date": "2017-09-23T13:16:45.703Z",
"build_snapshot": false,
"lucene_version": "6.6.1"
},
"tagline": "You Know, for Search"
}

**Comment by samdark** [comment]
2.1.x

**Comment by AnticDroid** [comment]
didn't help

**Comment by samdark** [comment]
@GHopperMSK have you checked with 2.1 branch?

**Comment by AnticDroid** [comment]
Depend on minimum stability
On stable use yiisoft/yii2-elasticsearch (2.0.5) and it work fine
Errors appear on  dev stability and "yiisoft/yii2-elasticsearch": "~2.1"

**Comment by AnticDroid** [comment]
Add description about steps for reproduce

**Comment by GHopperMSK** [comment]
It doesn't depend on `elasticsearch` version, but on `minimum-stability` value. 

Here is infinity loop in `\yii\elasticsearch\ActiveDataProvider`:
```
getModels()
prepare()
prepareModels()
getPagination()
prepareTotalCount()
getQueryResults()
prepare()
```

We have to rethink #16951! Specifically:
```
if (($this->_pagination !== false) && ($this->_pagination->totalCount === null)) {
            if ($this->_totalCount === null) {
                $this->setTotalCount($this->prepareTotalCount());
            }
            $this->_pagination->totalCount = $this->_totalCount;
        }
```

**Comment by taobig** [comment]
Change `yii\data\BaseDataProvider`,  make sure that `prepareTotalCount()` can only be called for the first time in `getPagination()`
or
Change `yii\elasticsearch\ActiveDataProvider`, make sure that `prepareTotalCount()` shouldn't call `$this->getPagination()`
Do you have any other ideas?

**Comment by GHopperMSK** [comment]
Let`s look at
https://github.com/yiisoft/yii2-elasticsearch/blob/0c2fa9f930d31640c4cb36f4b142f43f61895d99/ActiveDataProvider.php#L82-L107

First we call `getPagination()`, `getSort()` and only after that `$query->search()`. Here is my offer:
```
    protected function prepareModels1()
    {
        if (!$this->query instanceof Query) {
            throw new InvalidConfigException('The "query" property must be an instance "' . Query::className() . '" or its subclasses.');
        }

        $query = clone $this->query;
        $results = $query->search($this->db);
        $this->setQueryResults($results);

        if (($pagination = $this->getPagination()) !== false) {
            // pagination fails to validate page number, because total count is unknown at this stage
            $pagination->validatePage = false;
            $query->limit($pagination->getLimit())->offset($pagination->getOffset());
        }
        if (($sort = $this->getSort()) !== false) {
            $query->addOrderBy($sort->getOrders());
        }

        if ($pagination !== false) {
            $pagination->totalCount = $this->getTotalCount();
        }

        return $results['hits']['hits'];
    }
```
It works, but I didn't run tests yet.

**Comment by taobig** [comment]
```
$this->setQueryResults(is_array($result)?$result:[]);//changed, the param must be an array
```

**Comment by taobig** [comment]
I don't  think  this is an efficient solution, query will be executed twice. And the method will fetch **"all records"** at the first query.

**Comment by GHopperMSK** [comment]
> I don't think this is an efficient solution, query will be executed twice. And the method will fetch **"all records"** at the first query.
The solution doesn't add any queries, it just rearrange them. 

But in general I agree with you. There are many places have to be refactored.

**Comment by taobig** [comment]
I' sorry, I overlooked your code. There is no second query.

**Comment by AnticDroid** [comment]
Please apply this path for  2.1.x-dev

**Comment by samdark** [comment]
@GHopperMSK

**Comment by yuniorsk** [comment]
Hi guys, PR #204 introduced regression that's breaking sorting and pagination in data provider. It is because query is executed before pagination and sort methods are applied.

**Comment by samdark** [comment]
@GHopperMSK any other idea about fixing it?

**Comment by GHopperMSK** [comment]
> @GHopperMSK any other idea about fixing it?

I have a few ideas, but it will take some time.

**Comment by samdark** [comment]
Would these require changed in framework itself?

**Comment by GHopperMSK** [comment]
I don't think so. But as you know, it is quite unpredictable )
I think I will get some essential data during this weekend.

**Comment by GHopperMSK** [comment]
The current solution isn't optimal due to it makes redundant request for obtain totalCount. For solving this situation I need  `BaseDataProvider::_pagination` and `BaseDataProvider::_totalCount` to be private members, but they are in kernel.
@samdark What do you think?

**Comment by GHopperMSK** [comment]
In general, it solved. You are welcome for checking.

**Comment by machour** [comment]
Seems to be affecting yii2-sphinx as well: https://travis-ci.org/yiisoft/yii2-sphinx/jobs/495100578

**Comment by samdark** [comment]
Yii 2 change reverted. I'll clean up commits to ES as well.
