### ISSUE TITLE
BadRequestHttpException - not csrf. It may need a GET method?

### ISSUE THREAD

**Issue by grozzzny** [yiisoft/yii2-elasticsearch#205]
https://github.com/yiisoft/yii2-elasticsearch/blob/decb81344d1168d31e370fc03450ee4a344dade5/DebugPanel.php#L105

**Comment by grozzzny** [comment]
> Спасибо за размещение в нашем вопрос tracker.
> Для того, чтобы правильно помочь вам, нам нужна Дополнительная информация
> 
> * Когда возникает проблема?
> * Что вы видите?
> * Каков был ожидаемый результат?
> * Можете ли вы предоставить нам stacktrace? (Факультативный
> * У вас есть точный код для его воспроизведения? Может быть PHPUnit тесты, которые не удается? (Факультативный
> 
> Спасибо!
> 
> _Это автоматизированная комментарий, срабатывает путем добавления метки `status:need more info`._

Elasticsearch Queries in the debug panel. When you click on «run query».

Return:
```
Previous exception:
yii\web\BadRequestHttpException: Не удалось проверить переданные данные. in /home/www/front/vendor/yiisoft/yii2/web/Controller.php:166
Stack trace:
#0 /home/www/front/vendor/yiisoft/yii2-debug/src/controllers/DefaultController.php(65): yii\web\Controller->beforeAction(Object(yii\elasticsearch\DebugAction))
#1 /home/www/front/vendor/yiisoft/yii2/base/Controller.php(155): yii\debug\controllers\DefaultController->beforeAction(Object(yii\elasticsearch\DebugAction))
#2 /home/www/front/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('elasticsearch-q...', Array)
#3 /home/www/front/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('debug/default/e...', Array)
#4 /home/www/front/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#5 ../web/index.php(18): yii\base\Application->run()
#6 {main}
```

**Comment by beowulfenator** [comment]
Fixed in PR #227.
