### ISSUE TITLE
Is valid data provider for tests?

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/yii2-elasticsearch#215]
I don't understand if this condition has a valid format:

`
'id' => ['`id`=`id` and 1' => 1]
`

@samdark  Is it right?

https://github.com/yiisoft/yii2-elasticsearch/blob/1e6561ee3dd82188f1134e2bbbb52ff84bd19ce7/tests/ActiveRecordTest.php#L969

**Comment by samdark** [comment]
No but that's intended. The test is called "illegalValuesForFindByCondition".
