### ISSUE TITLE
Comment out the empty settings line in the guide

### ISSUE THREAD

**Issue by mcki0127** [yiisoft/yii2-elasticsearch#218]
### What steps will reproduce the problem?
Copy the example code without altering the settings line.

### What's expected?
It should work as expected.

### What do you get instead?
An error because it's passing an empty array:

`java.util.ArrayList cannot be cast to java.util.Map`

This can take a fair amount of time to troubleshoot for someone who is new to ES and this extension (like me.)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       |
| PHP version      |
| Operating system |

**Comment by machour** [comment]
What part of the guide are you referring to? (Url)
What would you add as indication?

**Comment by mcki0127** [comment]
https://github.com/yiisoft/yii2-elasticsearch/blob/master/docs/guide/mapping-indexing.md
The settings line is the createIndex function.
Sorry, what do you mean about indication?

**Comment by machour** [comment]
Gotcha, should be fixed soon, thank you for letting us know.
