### ISSUE TITLE
I have failure in this line

### ISSUE THREAD

**Issue by dieend** [yiisoft/yii2-elasticsearch#22]
https://github.com/yiisoft/yii2-elasticsearch/blob/master/ActiveRecord.php#L329

What's the `reset` for? When I removed it, it works properly. With it, I received this error:
```
Invalid operand type was used: expecting an array

    1. in /opt/application/urbanindov2/vendor/yiisoft/yii2-elasticsearch/ActiveRecord.php  at line 329 
```

**Comment by cebe** [comment]
can you show the code that causes the problem?

**Comment by dieend** [comment]
```
{
    "queryParts": {
        "fields": [
            "id"
        ],
        "size": 100,
        "query": {
            "filtered": {
                "filter": {
                    "bool": {
                        "must": [
                            {
                                "term": {
                                    "isRemoved": 0
                                }
                            },
                            {
                                "terms": {
                                    "status": [
                                        1,
                                        4
                                    ]
                                }
                            },
                            {
                                "term": {
                                    "specials": 1
                                }
                            }
                        ]
                    }
                }
            }
        }
    },
    "index": "IndexName",
    "type": "Type",
    "options": []
}
```

That is the value of `commandConfig` at https://github.com/yiisoft/yii2-elasticsearch/blob/master/ActiveQuery.php#L153

**Comment by cebe** [comment]
I mean the PHP code that creates the query

**Comment by petrabarus** [comment]
Isn't it enough info if I put the row content below?

```
array (
  '_index' => 'properties',
  '_type' => 'property',
  '_id' => '546519901',
  '_score' => 1,
  'fields' => 
  array (
    'id' => '546519901',
  ),
)
```

Is it because the ES we are using is 0.9?

**Comment by petrabarus** [comment]
Okay it seems that it's because we are using ES 0.9

https://www.elastic.co/guide/en/elasticsearch/reference/current/_return_values.html

> Field values, in response to the fields parameter, are now always returned as arrays. A field could have single or multiple values, which meant that sometimes they were returned as scalars and sometimes as arrays. By always returning arrays, this simplifies user code. The only exception to this rule is when fields is used to retrieve metadata like the routing value, which are always singular. Metadata fields are always returned as scalars.

**Comment by cebe** [comment]
yep, yii requires 1.0 or greater: https://github.com/yiisoft/yii2-elasticsearch#requirements
