### ISSUE TITLE
[ElasticSearch 7+]Removal of mapping types

### ISSUE THREAD

**Issue by vistart** [yiisoft/yii2-elasticsearch#225]
### What steps will reproduce the problem?

ElasticSearch removed the mapping type from version 7.0. [[Removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html)]
As a result, all current releases are completely incapable of working in ElasticSearch 7.0 and above.

### What's expected?

Remove the mapping type.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.16
| PHP version      | 7.2.17
| Operating system | Any
| ElasticSearch Version | 7.0.0+

**Comment by beowulfenator** [comment]
Extension is now compatible with ES7.
