### ISSUE TITLE
plan for elasticSearch7 ？ 2020 will coming。

### ISSUE THREAD

**Issue by chief725** [yiisoft/yii2-elasticsearch#237]
plan for elasticSearch7 ？ 2020 will coming。

hope support es7 in 2020

thanks

**Comment by machour** [comment]
#225 is about support for v7.

**Comment by karthiparthi** [comment]
when we expect elasticsearch 7 for yii2

**Comment by samdark** [comment]
Not until #232, #233 are solved.
