### ISSUE TITLE
ElasticsearchTarget::prepareMessage returns array for message

### ISSUE THREAD

**Issue by maxlyaptsev** [yiisoft/yii2-elasticsearch#239]
### What steps will reproduce the problem?
throw new \Exception('some Exception');

### What's expected?
adding log message into elasticsearch

### What do you get instead?

```json
{  
   "type":"mapper_parsing_exception",
   "reason":"failed to parse field [message] of type [text] in document with id 'Pox9uWsB6EfKcgFq8qKK'",
   "caused_by":{  
      "type":"illegal_state_exception",
      "reason":"Can't get text on a START_OBJECT at 1:128"
   }
}
```
### Additional info

If message is instance of Error class -  incoming data goes thought VarDumper::export. And we have proper string.  
It happens if I do smth like this: `throw new wtf\Exception('some Exception');`
And then `\yii\base\ErrorHandler::logException`  insert Error class into `Yii::error` instead of `Exception`. Because of this it works good. 

But normal exceptions catches earlier and we'v got an array.

`\yii\elasticsearch\ElasticsearchTarget::prepareMessage`

```php
        if ($text instanceof \Exception) {
            //convert exception to array for easier analysis
            $result['message'] = [
                'message' => $text->getMessage(),
                'file' => $text->getFile(),
                'line' => $text->getLine(),
                'trace' => $text->getTraceAsString(),
            ];
        } elseif (is_array($text) || is_string($text)) {
            $result['message'] = $text;
        } else {
            $result['message'] = VarDumper::export($text);
        }
````

Do I have to use logstash? And it is proper behaviour?

| Q                | A
| ---------------- | ---
| Yii version   2.0.20    |
| PHP version   7.2.15   |
| Operating system |

**Comment by beowulfenator** [comment]
Hi! I've been using this target for a while and I can tell you it is clearly not a good practice. Consider what would happen if the connection to ElasticSearch became slow or unreliable at the time of logging. I think it's a much better idea to write logs to a file and parse them with another utility (in my case FileBeat).

I've solved the exception problem by adding another condition (`if ($text instanceof \Exception || $text instanceof \Error)`). That, at least, fixes the problem short-term.
