### ISSUE TITLE
Can't set boolean options

### ISSUE THREAD

**Issue by yunniko** [yiisoft/yii2-elasticsearch#242]
| Q                | A
| ---------------  | ---
| Yii version         | 2
| PHP version      | 7.3 and 5.6
| ES version         | 7.3 and 6.4

When I trying to set 'track_total_hits' to true, http_build_query (which used in Connection->createUrl for convert options to query string) converts boolean to integer.

Every part of json is hardly defined and no possibility to add custom one

**Comment by beowulfenator** [comment]
Seems to be fixed in https://github.com/yiisoft/yii2-elasticsearch/pull/245, but can not be merged without unit tests.

**Comment by B0rner** [comment]
I have encountered the same problem. I am using ES 7 with Yii2 and ActiveDataProvider in conjunction with ListView widget. This usually works very well in Yii2. However, the behavior of at >10000 hits is not valid.
Setting `->addOptions(['track_total_hits' => 'true'])` outputs the correct number of hits. Nevertheless, the ListView widget stocks on results page Number >1000 (with 10 results per page).
The pagination header of the ListView shows more hits/pages ([999][1000][1001][1002]...). But: as soon as you go, with the ListView, to a result  above 10k, you get the error.

Of course, very rarely a user scrolls to the result page 1123, but if he does or if he jumps or a bot is reaching this point - the widget should work. It doesn't make sense to set the number of documents found to 10k - that confuses the users of the application. Nor does it make sense to display the correct number of hits when the widget cannot address the documents >10k. Handling big result lists -> this is exactly what pagination is used for.
