### ISSUE TITLE
The newest compatible ElasticSearch version for yii2-elasticsearch 2.1

### ISSUE THREAD

**Issue by letstestcode** [yiisoft/yii2-elasticsearch#247]
Hello. 

I have a question

I read in the description: "Extension version 2.1.x requires at least elasticsearch version 5.0". Is it means that the newest ElasticSearch version (7.3 for now) is compatible with yii2-elasticsearch 2.1? What the best compatible the newest version of ElasticSearch at this moment?

**Comment by samdark** [comment]
2.1 version of the extension should be much better compatible than 2.0. Try latest version of ElasticSearch with it.

**Comment by letstestcode** [comment]
So I have tried version 2.1 with the latest elasticsearch 7 and 6.
In the 7.3.0 it wasn't working even when I tried to create an index.
In the 6.8.2 I could to create, delete an index and to add a record. But any search isn't work except of the search by primary key.

```
$elastic = ElasticPage::getDb();

if ($elastic->createCommand()->indexExists(ElasticPage::index())) {
    ElasticPage::deleteIndex();
}
ElasticPage::createIndex();

$page = new ElasticPage();
$page->attributes = [
    'heading'       => 'test',
];
$page->setPrimaryKey(1);
$page->save();

$test1 = ElasticPage::get(1); // only this search works
$test2 = ElasticPage::find()->where([ 'heading' => 'test'])->all(); // it doesn't work
$test3 = ElasticPage::find()->all(); // it doesn't work
```

**Comment by letstestcode** [comment]
I have tested the code above with the elasticsearch version 5.6.16 and yii2-elasticsearch 2.1. It works correct with this version.

**Comment by letstestcode** [comment]
So you should write in the description that the extension version 2.1.x requires the elasticsearch version 5.x only because 6+ compatibility is very low for now.

**Comment by samdark** [comment]
OK.

**Comment by letstestcode** [comment]
> Extension version 2.1.x requires at least elasticsearch 5.x.
My English is very poor but "at least 5.x" means something like 5, 6, 7 and other 5+ can be used, isn't it? It's confusing a little.

**Comment by samdark** [comment]
Looks like your English is better than mine :) Fixed.

**Comment by letstestcode** [comment]
@samdark The code above works by very strange way. It finds only 1 record always and its always the record I have got by `$test1 = ElasticPage::get(1);`. And if I comment `$test1 = ElasticPage::get(1);` it finds nothing. Please can you explain me what I did wrong.

That's my model ElasticPage:
```php
<?php
namespace app\models;

class ElasticPage extends \yii\elasticsearch\ActiveRecord
{
    public function rules()
    {
        return [
            [['heading'], 'safe']
        ];
    }

    public function attributes()
    {
        return ['heading'];
    }

    /**
     * @return array This model's mapping
     */
    public static function mapping()
    {
        return [
            static::type() => [
                'properties' => [
                    'heading'       => ['type' => 'text'],
                ]
            ],
        ];
    }

    /**
     * Set (update) mappings for this model
     */
    public static function updateMapping()
    {
        $db = static::getDb();
        $command = $db->createCommand();
        $command->setMapping(static::index(), static::type(), static::mapping());
    }

    /**
     * Create this model's index
     */
    public static function createIndex()
    {
        $db = static::getDb();
        $command = $db->createCommand();
        $command->createIndex(static::index(), [
            'mappings' => static::mapping(),
        ]);
    }

    /**
     * Delete this model's index
     */
    public static function deleteIndex()
    {
        $db = static::getDb();
        $command = $db->createCommand();
        $command->deleteIndex(static::index(), static::type());
    }
}
```
How it works.
Example 1
```php
$test1 = ElasticPage::get(1); // the code below finds only the record by primaryKey=1
$test2 = ElasticPage::find()->where([ 'heading' => 'test'])->all();
$test3 = ElasticPage::find()->all(); 
```
Example 2
```php
//$test1 = ElasticPage::get(1); // when this line is commented nothing is found by the code below
$test2 = ElasticPage::find()->where([ 'heading' => 'test'])->all();
$test3 = ElasticPage::find()->all(); 
```

**Comment by samdark** [comment]
Have you called createIndex() to create an index to search by?

**Comment by letstestcode** [comment]
> Have you called createIndex() to create an index to search by?

The full code looks like:
```php
$elastic = ElasticPage::getDb();

if ($elastic->createCommand()->indexExists(ElasticPage::index())) {
    ElasticPage::deleteIndex();
}
ElasticPage::createIndex();

$page = new ElasticPage();
$page->attributes = [
    'heading'       => 'test',
];
$page->setPrimaryKey(1);
$page->save();

$test1 = ElasticPage::get(1);
$test2 = ElasticPage::find()->where([ 'heading' => 'test'])->all();
$test3 = ElasticPage::find()->all();
```

**Comment by samdark** [comment]
No immediate idea then try asking at forums: https://forum.yiiframework.com/c/yii-2-0/general-discussions

**Comment by letstestcode** [comment]
Looks like the problem was the delay before refreshing index of ElasticSearch. In the code above it can be resolved by running `$elastic->createCommand()->refreshIndex(ElasticPage::index());` before searching.
