### ISSUE TITLE
Debugger tool fails to run the query [v6.8.1]

### ISSUE THREAD

**Issue by tunecino** [yiisoft/yii2-elasticsearch#248]
### What steps will reproduce the problem?
Click on `run query` in Elasticsearch tab under debugger tool.

### What's expected?
Get query output.

### What do you get instead?
```
Exception (Elasticsearch Database Exception) 'yii\elasticsearch\Exception' with message 'Elasticsearch request failed with code 400. Response body:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse value [1] as only [true] or [false] are allowed."}],"type":"illegal_argument_exception","reason":"Failed to parse value [1] as only [true] or [false] are allowed."},"status":400}' 
```
### Additional info
The error is thrown due to `?pretty=1`in the url generated by `yii\elasticsearch\DebugAction`. Changing that to `?pretty=true` instead fixes it for **v6.8.1**. But I have no idea if this is a BC for previous versions.

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.25
| PHP version      | 7.3.5
| Elastic version | 6.8.1

**Comment by beowulfenator** [comment]
Even 1.7 expects `pretty=true`. No problems with BC here.

https://www.elastic.co/guide/en/elasticsearch/reference/1.7/common-options.html#_pretty_results

**Comment by beowulfenator** [comment]
PR pending
