### ISSUE TITLE
ActiveRecord didn`t load attributes to it  private _attributes by setAttributes

### ISSUE THREAD

**Issue by xianghuawe** [yiisoft/yii2-elasticsearch#253]
##### environment info:

+ php version 5.6
+ yii2 version 2.0.14
+ yii2-elasticsearch version 2.0.5

when i use yii\elasticsearch\ActiveRecord to store my city data , i found some problem with 
 **load**  function ？ it just didn`t set attribute to yii\db\BaseActiveRecord priviate $_attributes;
and i toke a look at 

```php
public function setAttributes($values, $safeOnly = true)
    {
        if (is_array($values)) {
            $attributes = array_flip($safeOnly ? $this->safeAttributes() : $this->attributes());
            foreach ($values as $name => $value) {
                if (isset($attributes[$name])) {
                    $this->$name = $value;
                } elseif ($safeOnly) {
                    $this->onUnsafeAttribute($name, $value);
                }
            }
        }
    }
```

 when i load attribute by yii\elasticsearch\ActiveRecord  ,i
t did not load to _attribute ;so after save that step,
 i can`t store data to my elasticsearch

after hours ,i found this function below seems doing well on setAttribute one by one.....

```php
public function setAttribute($name, $value)
    {
        if ($this->hasAttribute($name)) {
            if (
                !empty($this->_relationsDependencies[$name])
                && (!array_key_exists($name, $this->_attributes) || $this->_attributes[$name] !== $value)
            ) {
                $this->resetDependentRelations($name);
            }
            $this->_attributes[$name] = $value;
        } else {
            throw new InvalidArgumentException(get_class($this) . ' has no attribute named "' . $name . '".');
        }
    }
```

 
### What's expected?

save data to  elasticsearch

### What do you get instead?
overwirte setAttibutes function in my baseEsActiveRecord

```php
/**
     * @inheritDoc
     */
    public function setAttributes($values, $safeOnly = true)
    {
        if (is_array($values)) {
            $attributes = array_flip($safeOnly ? $this->safeAttributes() : $this->attributes());
            foreach ($values as $name => $value) {
                if (isset($attributes[$name])) {
                    $this->setAttribute($name, $value);
                    $this->$name = $value;
                } elseif ($safeOnly) {
                    $this->onUnsafeAttribute($name, $value);
                }
            }
        }
    }
```

**Comment by beowulfenator** [comment]
@xianghuawe, are you sure your attributes are properly declared in `$rules`? If there is no rule for an attribute, then by default `load()` will not process them. Using `setAttributes` with `$safeOnly` set to true will.
Can you please check and close the issue if this is the case?

**Comment by xianghuawe** [comment]
recode like that ,did not found any problem , sorry for the disturb
