### ISSUE TITLE
yii2 elasticsearch not supported for elasticsearch 7 version 

### ISSUE THREAD

**Issue by karthiparthi** [yiisoft/yii2-elasticsearch#254]
### What's expected?
working on yii2 with elasticsearch 7 but it is not supported (typless not supported) 

### What do you get instead?
Yii2 elasticsearch getting following error: 
```
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: yii\elasticsearch\Query::emulateExecution

```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version       |2.0
| PHP version      |7.1
| Operating system |Linux

**Comment by samdark** [comment]
Related to #232, #233

**Comment by beowulfenator** [comment]
ElasticSearch 7 is indeed not supported yet

**Comment by beowulfenator** [comment]
Now it is supported.
