### ISSUE TITLE
The Exception  "Trying to access array offset on value of type bool" when find a doc which not exists

### ISSUE THREAD

**Issue by qce7** [yiisoft/yii2-elasticsearch#258]
The issue may be affected by these two places.
https://github.com/yiisoft/yii2-elasticsearch/blob/c9ef9326474a11a9a024082fbe71747f9952672d/Connection.php#L549-L550

https://github.com/yiisoft/yii2-elasticsearch/blob/c9ef9326474a11a9a024082fbe71747f9952672d/ActiveRecord.php#L150-L153

The version of elasticsearch is 7.5.1

**Comment by samdark** [comment]
Master branch or 2.1 branch?

**Comment by qce7** [comment]
@samdark 2.1 branch

**Comment by lubobill1990** [comment]
This happens because in the newest version of elasticsearch 6, if a query can't find any result, such as 
```
curl -v http://127.0.0.1:9200/answer_dev/_doc/1
```
the response code is 404
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 9200 (#0)
> GET /answer_dev/_doc/1 HTTP/1.1
> Host: 127.0.0.1:9200
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< content-type: application/json; charset=UTF-8
< content-length: 62
<
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
{"_index":"answer_dev","_type":"_doc","_id":"1","found":false}%
```

The problem comes from the code in Connection httpRequest
```
} elseif ($responseCode == 404) {
            return false;
```

**Comment by lubobill1990** [comment]
I have submitted a pull request about this issue, please have a check.

**Comment by samdark** [comment]
@lubobill1990 should pull request be made against 2.1 branch?

**Comment by lubobill1990** [comment]
@samdark I think should be made to both branches. The related code is the same.

**Comment by beowulfenator** [comment]
PR pending.
