### ISSUE TITLE
How to inject hasMany model to ElasticSearch results?

### ISSUE THREAD

**Issue by Miri92** [yiisoft/yii2-elasticsearch#261]
Hi, Sorry for my poor English and stupid question. Currently i have Yii2 app which ElasticSearch works in here. But i need to call hasMany relationship model in ElasticSearch results. I looked documentation but i can't find anything about my citation.

### My Controller
PostElastic::instance()
        ->search($query, 10)
       ->joinWith('categories');

error
Calling unknown method: common\models\elastic\Post::joinWith()

**Comment by beowulfenator** [comment]
There's no `joinWith` because ElasticSearch does not support joins. You can still use `with` to eager-load your relation, if you need to. But there is no way to execute a join and filter on attributes of the joined model.
