### ISSUE TITLE
function createIndex() got 400 from ElasticSearch 7.7

### ISSUE THREAD

**Issue by gzldx** [yiisoft/yii2-elasticsearch#273]
[requestMethod] => PUT
[requestUrl] => http://127.0.0.1:9200/problems
[requestBody] => {"mappings":{"problem":{"properties":{"message":{"type":"text"}}}}}
[responseCode] => 400
response:
[type] => mapper_parsing_exception
[reason] => Root mapping definition has unsupported parameters:  [problem : {properties={message ={type=text}}}]

yii2-elasticsearch version: dev-master 6bc1d67

| Q                | A
| ---------------- | ---
| Yii version       | 2.x
| PHP version      |  7.3
| Operating system | unix

**Comment by beowulfenator** [comment]
For those looking at this issue in the future :)

ES7 does not support type anymore, so the correct request body is `{"mappings":{"properties":{"message":{"type":"text"}}}}`. In this case the extension itself is agnostic of the request body contents. Correct value must be passed by the developer.
