### ISSUE TITLE
Removed 2.1.* tag

### ISSUE THREAD

**Issue by nikoole** [yiisoft/yii2-elasticsearch#278]
I am trying to use command line from documentation: 
`composer require --prefer-dist yiisoft/yii2-elasticsearch:"~2.1.0"`

Expecting installing of extension which supports Elasticsearch version 5.x

Getting:
```
Problem 1
    - The requested package yiisoft/yii2-elasticsearch ~2.0.x-dev exists as yiisoft/yii2-elasticsearch[2.0.0, 2.0.0-alpha, 2.0.0-beta, 2.0.0-rc, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, dev-json-bigint, dev-master, 2.0.x-dev, dev-unique-validator] but these are rejected by your constraint.
```

Yii version: 2.0.6
PHP version: 7.2
Operating system: tested on Ubuntu/Macs

**Comment by samdark** [comment]
Please try again. I've corrected an alias: https://packagist.org/packages/yiisoft/yii2-elasticsearch#dev-master
