### ISSUE TITLE
AWS Elasticsearch service compatibility

### ISSUE THREAD

**Issue by andrey-bahrachev** [yiisoft/yii2-elasticsearch#28]
Hey guys!
As you may have heard, AWS have launched Elasticsearch service recently which is really great, and I decided to take it for a spin, but this extension doesn't work with it in its current state. There are two points of failure with it.
Firstly, AWS ES endpoint returns 'text/plain' content type instead of 'application/json' - that's where the `Connection->httpRequest()` method fails. And secondly, ES nodes there don't have `'http_address'` property for some reason, that's why `Connection->open()` method and a couple of others that rely on that property fail.
I hope that will be fixed, so that those who need it don't need to fork or hack the code :) Thanks!

**Comment by samdark** [comment]
@andrey-bahrachev do you want to work on a pull request since you're on it?

**Comment by andrey-bahrachev** [comment]
@samdark Ah, ok, why not?

**Comment by samdark** [comment]
Merged https://github.com/yiisoft/yii2-elasticsearch/commit/fd78b6efff994a4071138607ac6f810e4f08119b. Thanks!

**Comment by samdark** [comment]
https://forums.aws.amazon.com/thread.jspa?threadID=217748&tstart=0
