### ISSUE TITLE
updateAllCounters

### ISSUE THREAD

**Issue by lookbackagain** [yiisoft/yii2-elasticsearch#285]
![image](https://user-images.githubusercontent.com/7089466/87505117-a690eb80-c69a-11ea-892a-163d106eee62.png)

```php
foreach ($primaryKeys as $pk) {
    $script = '';
    foreach ($counters as $counter => $value) {
        $script .= "ctx._source.{$counter} += params.{$counter};\n";
    }
    $bulkCommand->addAction(["update" => ["_id" => $pk]], [
        'script' => [
            'inline' => $script,
            'params' => $counters,
            'lang' => 'painless',
        ],
    ]);
}
```

there should changed with `$script .= "ctx._source.$counter += $value";`?

**Comment by beowulfenator** [comment]
Why should it be changed? The variable `$value` holds the name of the counter. The variable `$counters` holds the values of all your counters. As you see, we are passing `$counters` as a parameter to the script.

In your case you have a counter named `"view"`, and that counter is being updated to a new value. So `params.view` should be equal to the value of your counter.


Can you show me how exactly the script fails (the whole error message?) Also, which version of Elasticsearch are you using?

**Comment by lookbackagain** [comment]
'name' => 'yiisoft/yii2-elasticsearch',
            'version' => '2.0.4.0',
         
          foreach ($counters as $counter => $value) {
                $script .= "ctx._source.$counter += $counter;\n";
            }

          Elasticsearch version is 5.6.3

        my code : updateAllCounters(['view'=>1],["_id"=>$id]);

![image](https://user-images.githubusercontent.com/7089466/87616159-080e9400-c747-11ea-83f0-d334dc6175d4.png)

**Comment by lookbackagain** [comment]
> Why should it be changed? The variable `$value` holds the name of the counter. The variable `$counters` holds the values of all your counters. As you see, we are passing `$counters` as a parameter to the script.
> 
> In your case you have a counter named `"view"`, and that counter is being updated to a new value. So `params.view` should be equal to the value of your counter.
> 
> Can you show me how exactly the script fails (the whole error message?) Also, which version of Elasticsearch are you using?

replied,thanks

**Comment by beowulfenator** [comment]
You are using the incorrect version of the extension. None of the stable versions are compatible with ES5+. Install the latest from dev-master.
