### ISSUE TITLE
How to add synonyms in ES?

### ISSUE THREAD

**Issue by SobhieSad** [yiisoft/yii2-elasticsearch#293]
Hi, @samdark 
I need to add synonyms to a text field before inserting it in ES DB,  what is the right way to support multi-languages?  I don't find a clear way from docs for inserting text with its synonyms.

**Comment by beowulfenator** [comment]
Either this for true synonyms:
https://www.youtube.com/watch?v=i01Um2HEAbk

Or just make it simple, instead of `$model->animal = "dog"` do `$model->animal = ["dog", "hund", "chien"]`.

**Comment by SobhieSad** [comment]
@beowulfenator thank you
