### ISSUE TITLE
There is a problem with the spliced URL when using delete

### ISSUE THREAD

**Issue by hkui** [yiisoft/yii2-elasticsearch#295]
### What steps will reproduce the problem?
```php
$connect=\Yii::$app->get('es');

 $r=$connect->createCommand()->delete('book','book',null,['id'=>1]);
 var_dump($r);
```

### What do you get instead?
{"error":"Incorrect HTTP method for uri [/book/_doc/?id=1] and method [DELETE], allowed: [POST]","status":405}

### Additional info
It is mainly the problem of splicing URL when use the below function 

```php
 private function createUrl($path, $options = [])
    {
        if (!is_string($path)) {
            $url = implode('/', array_map(function ($a) {
                return urlencode(is_array($a) ? implode(',', $a) : $a);
            }, $path));
            if (!empty($options)) {
                $url .= '?' . http_build_query($options);
            }
        } else {
            $url = $path;
            if (!empty($options)) {
                $url .= (strpos($url, '?') === false ? '?' : '&') . http_build_query($options);
            }
        }
        $node = $this->nodes[$this->activeNode];
        $protocol = isset($node['protocol']) ? $node['protocol'] : $this->defaultProtocol;
        $host = $node['http_address'];
        return [$protocol, $host, $url];
    }
```
The URL it generates is "/book/_doc/?id=1"

How can I use delete () correctly？

| Q                | A
| ---------------- | ---
| Yii version       |2.0.39.3
| PHP version     | 7.2.14
| Operating system |centos7

**Comment by samdark** [comment]
What should be generated?

**Comment by hkui** [comment]
> What should be generated?

/book/_doc/1

**Comment by beowulfenator** [comment]
The reason you're getting the error is the name of the variable. When you write `['id' => 1]` semantically it's the same as `['foobar' => 1]`, there's no special meaning attached to the name `id`. Try `['_id' => 1]`.
