### ISSUE TITLE
the cluster does not work alway get first node。。

### ISSUE THREAD

**Issue by fuzongtang** [yiisoft/yii2-elasticsearch#303]
always get first node。。。
### Additional info

| Q                | A
| ---------------- | ---
| Yii version       |
| PHP version      |
| Operating system |

**Comment by fuzongtang** [comment]
```php
'elasticsearch' => [
            'class' => 'yii\\elasticsearch\\Connection',
            'nodes' => [
                ['http_address' => '172.17.129.190:9200'],
                ['http_address' => '172.17.129.179:9200'],

                // configure more hosts if you have a cluster
            ],
            // set autodetectCluster to false if you don't want to auto detect nodes
            'autodetectCluster' => true,
            'dslVersion' => 5, // default is 5
        ],
```

When the first node hangs up, the system reports an error。
```php
Elasticsearch Database Exception – yii\elasticsearch\Exception
Elasticsearch request failed: 7 - Failed to connect to 172.17.129.190 port 9200: Connection refused
Error Info: Array
(
    [requestMethod] => GET
    [requestUrl] => http://172.17.129.190:9200/_nodes/_all/http
    [requestBody] => 
    [responseHeaders] => Array
        (
        )

    [responseBody] => 
)
```
So have to make sure that the first node works ？
Won't the cluster switch automatically?

**Comment by fuzongtang** [comment]
> ```
> 'elasticsearch' => [
>             'class' => 'yii\\elasticsearch\\Connection',
>             'nodes' => [
>                 ['http_address' => '172.17.129.190:9200'],
>                 ['http_address' => '172.17.129.179:9200'],
> 
>                 // configure more hosts if you have a cluster
>             ],
>             // set autodetectCluster to false if you don't want to auto detect nodes
>             'autodetectCluster' => true,
>             'dslVersion' => 5, // default is 5
>         ],
> ```
> 
> When the first node hangs up, the system reports an error。
> 
> ```
> Elasticsearch Database Exception – yii\elasticsearch\Exception
> Elasticsearch request failed: 7 - Failed to connect to 172.17.129.190 port 9200: Connection refused
> Error Info: Array
> (
>     [requestMethod] => GET
>     [requestUrl] => http://172.17.129.190:9200/_nodes/_all/http
>     [requestBody] => 
>     [responseHeaders] => Array
>         (
>         )
> 
>     [responseBody] => 
> )
> ```
> 
> So have to make sure that the first node works ？
> Won't the cluster switch automatically?

@knut 
@samdark 
@yii-bot 
@nergal

**Comment by beowulfenator** [comment]
This is the expected behavior. If the extension retried connections to different nodes, this would be a debugging nightmare. If you need that kind of behavior, set up a coordinator node in your cluster:

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#coordinating-only-node

**Comment by fuzongtang** [comment]
> This is the expected behavior. If the extension retried connections to different nodes, this would be a debugging nightmare. If you need that kind of behavior, set up a coordinator node in your cluster:
> 
> https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#coordinating-only-node

If so, what is the point of cluster configuration?
```php
'nodes' => [
                ['http_address' => '172.17.129.190:9200'],
                ['http_address' => '172.17.129.179:9200'],

                // configure more hosts if you have a cluster
            ],
```
