### ISSUE TITLE
Add Support for Runtime Mappings

### ISSUE THREAD

**Issue by mabentley85** [yiisoft/yii2-elasticsearch#311]
Adding support for Elasticsearch [Runtime Mappings](https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime.html) added in version 7.11 seems like it would be a pretty simple feature addition.

I've already started working on it in this [forked branch](https://github.com/mabentley85/yii2-elasticsearch/tree/Add-Runtime-Mappings)

The implementation is very similar to adding `scriptFields`.

How should I proceed developing this feature?

**Comment by samdark** [comment]
@mabentley85 in a branch. Then do a pull request.

**Comment by mabentley85** [comment]
@samdark Thanks! Just created #313
