### ISSUE TITLE
ErrorException: Return type of yii\elasticsearch\BatchQueryResult::current() incompatible with Iterator::current(): mixed

### ISSUE THREAD

**Issue by warton** [yiisoft/yii2-elasticsearch#332]
### What steps will reproduce the problem?
Any try to call the method each on Query object eg.: yii\elasticsearch\Query->each('5m')

### What's expected?
Correct response without exception.

### What do you get instead?
PHP Fatal error:  During inheritance of Iterator: Uncaught yii\base\ErrorException: Return type of yii\elasticsearch\BatchQueryResult::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/yiisoft/yii2-elasticsearch/BatchQueryResult.php:196

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       |2.0.47
| PHP version      |8.1.18
| Operating system |Docker: Linux ee81f300eee8 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux

**Comment by samdark** [comment]
`[\ReturnTypeWillChange]` should be added. @warton do you have time for a pull request?
