### ISSUE TITLE
Return boolean values instead of integer on ActiveRecord::updateInternal

### ISSUE THREAD

**Issue by agostlg** [yiisoft/yii2-elasticsearch#35]
I'm having an issue where BaseActiveRecord::save() do

`return $this->update($runValidation, $attributeNames) !== false;` 

and the return from \yii\elasticsearch\ActiveRecord::updateInternal returns integer, which makes the model who is calling save() receive true even when the update was not successful.

If you guys agree with the change I can make the pull request for it.

**Comment by samdark** [comment]
If update wasn't successful it should return 0 or false if validation failed. That is expected, isn't it?

**Comment by agostlg** [comment]
"If update wasn't successful it should return 0 or false if validation failed. That is expected, isn't it?"

Yes for false, but if you return 0 the save method from \yii\db\BaseActiveRecord line 584 will return true:
`return $this->update($runValidation, $attributeNames) !== false;`

**Comment by samdark** [comment]
Well, if zero rows affected because of condition matches no rows, it is still considered a success. This is by design.
