### ISSUE TITLE
Unexpected handling of and/or filter conditions

### ISSUE THREAD

**Issue by beowulfenator** [yiisoft/yii2-elasticsearch#40]
Adding several conditions using `orWhere` results in an unexpected query structure:

    $query->where(['_id' => ['1']]);
    $query->orWhere(['_id' => ['2']]);
    $query->orWhere(['_id' => ['3']]);
    $query->orWhere(['_id' => ['4']]);

This produces the following query structure:

    {
      "filter":{
        "or":[{
            "or":[{
                "or":[
                  {"ids":{"values":["1"]}},
                  {"ids":{"values":["2"]}}
                ]
              },
              {"ids":{"values":["3"]}}
            ]
          },
          {"ids":{"values":["4"]}}
        ]
      }
    }

I would expect something like:

    {
      "filter":{
        "or":[
          {"ids":{"values":["1"]}},
          {"ids":{"values":["2"]}},
          {"ids":{"values":["3"]}},
          {"ids":{"values":["4"]}}
        ]
      }
    }

**Comment by cebe** [comment]
well, the logic is the same and this way it is much easier to implement. Is there a problem with this?

**Comment by beowulfenator** [comment]
Well, this definitely works. If this is the intended behavior, then never mind. Also, given that and/or/not are deprecated anyway, this is probably not important.
