### ISSUE TITLE
AND/OR/NOT filters/queries deprecated in favor of bool query

### ISSUE THREAD

**Issue by beowulfenator** [yiisoft/yii2-elasticsearch#41]
As of ES 2.0.0-beta1 the preferred way of handling boolean logic in filters and queries is the `bool` filter/query.

Should `QueryBuilder` class be updated to create a `bool` filter by default?

**Comment by cebe** [comment]
can you point me to the documentation about this? Also QueryBuilder only generates a bool filter from the "where" part. Bool query is quite different.

**Comment by beowulfenator** [comment]
There are several notable changes in the DSL. First, they seem to unify queries and filters. So there is no `bool` query and `bool` filter, now there is only `bool` query that works both in query context and filter context.

https://www.elastic.co/guide/en/elasticsearch/reference/2.1/query-filter-context.html

So, as you see, `and` filter has been first deprecated in favor of `and` query:
https://www.elastic.co/guide/en/elasticsearch/reference/2.1/query-dsl-and-filter.html

And `and` query itself has been deprecated in favor of `bool` query:
https://www.elastic.co/guide/en/elasticsearch/reference/2.1/query-dsl-and-query.html

The relevant discussion is here:
https://github.com/elastic/elasticsearch/issues/8960

**Comment by beowulfenator** [comment]
So right now our `Query` class has `$filters` property.

How about we replace it with 3 properties to store `must`, `should` and `must_not` clauses? And methods like `addMust()`, `addShould()` and `addMustNot()`? With this logic the root filter of the query will be the `bool` filter. And if the user adds something with `andWhere()` it just goes into the `must` clause.

**Comment by twisted1919** [comment]
`So right now our Query class has $filters property. How about we replace it with 3 properties to store must, should and must_not clauses?`
Don't do this, just don't. `$filters` property, just like `$query` one are perfectly fine as they are right now, allowing you to specify extra nested conditions.

**Comment by holycheater** [comment]
Filtered query equivalent is now bool query with filter clause.

**Comment by beowulfenator** [comment]
Not strictly required for ElasticSearch 1.7, and already fixed in the 2.1 branch.
