### ISSUE TITLE
ActiveQuery's updateAll only updates first 10 entries

### ISSUE THREAD

**Issue by beowulfenator** [yiisoft/yii2-elasticsearch#48]
When updating multiple models with `updateAll`, only first 10 entries get updated. This query attempts to fetch all primary keys that satisfy the provided `$condition`:
https://github.com/yiisoft/yii2-elasticsearch/blob/master/ActiveRecord.php#L580

However, by default its limit is set to 10 (at least in my ES 1.7), so it only gets the first 10 PKs. They get correctly updated afterwards using bulk API.

The problem is with such approach in general, as there is a limit to how far we can set the limit ([at least in ES 2.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html)).

One possible solution would be to either use an [external plugin](https://github.com/yakaz/elasticsearch-action-updatebyquery) that can update all documents based on a query, or somehow mimic its behavior using scripts.

Another option is getting those PKs with scan-and-scroll API and then updating using bulk API.

P.S.: Phpdoc summary of this function refers to SQL and is not accurate.

**Comment by cebe** [comment]
#39

**Comment by beowulfenator** [comment]
Yes, this is the same issue, but scan/scroll api is a much more fitting solution to returning large number of documents (or at least their PKs). There is a [pull request](https://github.com/yiisoft/yii2-elasticsearch/pull/30) where scroll api is implemented. If that was pulled into master, I could implement updateAll and deleteAll with scan/scroll. In fact, I am already doing that for my fork.

**Comment by beowulfenator** [comment]
Fixed in #51
