### ISSUE TITLE
Not able to fetch _id value as that is defined as private

### ISSUE THREAD

**Issue by mandalm** [yiisoft/yii2-elasticsearch#69]
In ActiveRecord 
```
private $_id;
```
due to this i am not able to access / read primary key value from _id from ```DetailView```

when i change to 
```
public $_id;
```

then it worked fine. When I do public then I can read in child class.

Let me know if i missing something or its a bug.

regards
Mithun Mandal

**Comment by cebe** [comment]
you can get if by calling `getPrimaryKey()`
