### ISSUE TITLE
Running out of memory on mass indexing

### ISSUE THREAD

**Issue by jepster** [yiisoft/yii2-elasticsearch#74]
If I'm indexing a mass of data (1000 - 2000 data rows) into my elasticsearch index and I'm running out of memory. This is the error message:

> PHP Fatal Error 'yii\base\ErrorException' with message 'Out of memory (allocated 2359296) (tried to allocate 3072 bytes)'

I'm indexing via the following code in class method:

```
    $otable = table::find()->each();

    foreach ($otable as $table) {

      $mymodel = new MyModel();
      $mymodel->id = $table->id;
      $mymodel->title = $table->title;
      $mymodel->teaser = $table->teaser;
      $mymodel->category = $table->category;
      $mymodel->sub_category = $table->sub_category;
      $mymodel->save();

    }

  }
```
Via each(); I'm already saving memory at "reading" data from database via batches.

Is there any method which saves from running out of memory on the indexing process?

**Comment by beowulfenator** [comment]
You could try reducing batch size. What is your current batch size?

**Comment by klimov-paul** [comment]
Does your `table` model has any behavior attached?

**Comment by jepster** [comment]
Thank you guys for the fast response.

@beowulfenator: I have Yii's default batch size. Default batch size is 100. That's probably not the problem.

@klimov-paul: No, it has no behaviour attached.

Any further ideas?

**Comment by klimov-paul** [comment]
Does you script save at least one row at ElasticSearch before error? How many rows are saved?

Does `MyModel` has any behavior attached?

**Comment by cebe** [comment]
> allocated 2359296

what is your php memory limit? this number looks weird to me, is this around 2MB?

@jepster it could be that the logger takes a lot of memory when not flushing log messages.

**Comment by AnatolyRugalev** [comment]
@jepster do you use MySQL PDO? Did you disabled `PDO::MYSQL_ATTR_USE_BUFFERED_QUERY` option? See #9269

**Comment by klimov-paul** [comment]
Closed unless more information provided
