### ISSUE TITLE
"network.bind_host: localhost" must be uncommented for usage by yii2-elasticsearch

### ISSUE THREAD

**Issue by jepster** [yiisoft/yii2-elasticsearch#75]
If I have the following option active (in the config file at /etc/elasticsearch/elasticsearch.yml)

> network.bind_host: localhost

then I cannot connect the elasticsearch server by my Yii 2 code.

But I "can" connect to it via cURL from the command line. E.g.:

> curl -X POST 'http://localhost:9200/tutorial/helloworld/1' -d '{ "message": "Hello World!" }'

So currently I'm using elasticsearch with "network.bind_host: localhost" switched off. This is unsecure. Everybody from the internet can access the index. How can I fix this?

**Comment by beowulfenator** [comment]
If you bind to localhost, does this work:

curl -X POST 'http://127.0.0.1:9200/tutorial/helloworld/1' -d '{ "message": "Hello World!" }'

If not, just update yii2-elastic config to use `localhost:9200`, not `127.0.0.1:9200`.

**Comment by jepster** [comment]
"127.0.0.1" and "localhost" are the same thing in this case. There's no difference if I use either the one or the other.

**Comment by cebe** [comment]
@jepster I had similar issues when chaning networks on my laptop. You have to restart elasticsearch every time your network configuration changes, e.g. other wlan, etc... Could that be related?

**Comment by cebe** [comment]
I have the following elasticsearch.yml config on my server:

```
network.host: 127.0.0.1
```

connection with yii:

```php
	'components.elasticsearch' => [
		'class' => 'yii\elasticsearch\Connection',
		'nodes' => [
			['http_address' => '127.0.0.1:9200'],
			// configure more hosts if you have a cluster
		],
	],
```

**Comment by cebe** [comment]
could it be that elasticsearch resolves `localhost` to IPv6 `::1` and yii tries to connect over IPv4?

You could check that by running `lsof -i`

**Comment by jepster** [comment]
Exactly! It was an issue with IPv6. My working settings looks now like follows:

```
'elasticsearch' => [
      'class' => 'yii\elasticsearch\Connection',
      'nodes' => [
        ['http_address' => '[::1]:9200'],
        // configure more hosts if you have a cluster
      ],
    ],
```
