### ISSUE TITLE
The configuration file should add a prefix

### ISSUE THREAD

**Issue by junezhou** [yiisoft/yii2-elasticsearch#79]
1. main-local.php
'elasticsearch' => [
            'class' => 'yii\elasticsearch\Connection',
            'nodes' => [
                ['http_address' => '127.0.04:9200'],
                // configure more hosts if you have a cluster
            ],
            'keyPrefix' => 'dev_'
],

2. Connection.php
class Connection extends Component
{
         public $keyPrefix = '';
}

3. ActiveRecord.php
public static function index()
 {
        $index =  Inflector::pluralize(Inflector::camel2id(StringHelper::basename(get_called_class()), '-'));
        $keyPrefix = self::getDb()->keyPrefix;
        return $keyPrefix.$index;
}

**Comment by beowulfenator** [comment]
If you like, you can implement your application-wide prefix in parameters, and then prepend it to index name whenever you extend `index()` in your models. For that matter, you can have a prefix in type too.

I believe that forcing this component to use an externally settable prefix is not the way to go.

**Comment by andreyderma** [comment]
Hi, i am using elasticsearch on AWS, and i get host like this: https://foo.bar.ap-southeast-1.es.amazonaws.com:443
How to force http_address using "https://", I read elasticsearch connection code, they hardcoded "http://",
Dirty way, I changed "http://" to "https://" and it works, Is there any proper way to use https?

**Comment by beowulfenator** [comment]
I've created a separate issue for the http/https problem:
https://github.com/yiisoft/yii2-elasticsearch/issues/82
