### ISSUE TITLE
Allow to connect to ES cluster using HTTPS

### ISSUE THREAD

**Issue by beowulfenator** [yiisoft/yii2-elasticsearch#82]
Currently, HTTP protocol is hardcoded. There should be a way to connect to ES cluster using HTTPS (useful for AWS).

To quote the original comment:
> Hi, i am using elasticsearch on AWS, and i get host like this: https://foo.bar.ap-southeast-1.es.amazonaws.com:443
How to force http_address using "https://", I read elasticsearch connection code, they hardcoded "http://",
Dirty way, I changed "http://" to "https://" and it works, Is there any proper way to use https?

**Comment by cebe** [comment]
are these ES instances open to public internet? how is access control handled?

**Comment by beowulfenator** [comment]
Solved by PR #107.
