### ISSUE TITLE
Setting a different port for elasticsearch does not work.

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2-elasticsearch#88]
I set my elastic search in config as follows:

```php
        'elasticsearch' => [
            'class' => 'yii\elasticsearch\Connection',
            'nodes' => [
                ['http_address' => '127.0.0.1:6273'],
                // configure more hosts if you have a cluster
            ],
        ],
```

Then i use a `yii\elasticsearch\ActiveRecord` instance to find the count. 

```php
$results = Topic::find()->count();
```

It turns out that elasticsearch is still trying to connect to the 9200 port.

> Elasticsearch request failed: 7 - Failed to connect to 127.0.0.1 port 9200: Connection refused

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.8
| PHP version      |7.0.2
| Operating system |win 7

**Comment by beowulfenator** [comment]
Just tested this locally, and it works. I can only assume you have an error in your config.

**Comment by Locustv2** [comment]
What can possibly be wrong with my config? I pasted it in the first post.

I tried changing the ip to `127.0.0.2:9200` (just for testing the error) and i get 

> Elasticsearch request failed: 7 - Failed to connect to 127.0.0.2 port 9200: Connection refused

I added a dump of the `$url` in `yii\elasticseatch\connection::httpRequest()`  on line 440 and another one in the if statement on line 450 and i `die()` immediately here.

I get 3 dumps for a single `find()->count()` as follows:

- (line 440) http://127.0.0.1:6273/_nodes
- (line 440) http://127.0.0.1:9200/topics/topic/_search?search_type=count
- (line 450) http://127.0.0.1:9200/topics/topic/_search?search_type=count

So i guess my config is good.

**Comment by beowulfenator** [comment]
Can you please see what your server is returning in line 157:

        $response = $this->httpRequest('GET', 'http://' . $host . '/_nodes');

Can it be that you are getting the new nodes from the server and they are incorrect?

**Comment by Locustv2** [comment]
Ok here are the results for _nodes:

```php
          'name' => string 'Warwolves' (length=9)
          'transport_address' => string '127.0.0.1:9300' (length=14)
          'host' => string '127.0.0.1' (length=9)
          'ip' => string '127.0.0.1' (length=9)
          'version' => string '2.3.3' (length=5)
          'build' => string '218bdf1' (length=7)
          'http_address' => string '127.0.0.1:9200' (length=14)
```

I was actually ssh tunnelling 6273 to 9200, so that was probably the cause of all this.

I don't think this is a serious issue. Will this be fixed or not?

Thanks

**Comment by beowulfenator** [comment]
Well, the problem is with your cluster. You are basically asking the cluster "what are the available nodes?" The cluster tells you of a node that is listening on port 9200. It doesn't know that this node is actually only reachable by you if you open port 6273 that is then mapped to 9200.

Active FTP has a similar problem (that's why it's almost never used).

Try setting the `autodetectCluster` property to `false`. That way yii will connect to the one and only node you've configured explicitly and you'll also save on one unnecessary http request (to the `_nodes` endpoint).

**Comment by beowulfenator** [comment]
@Locustv2, please respond if you have anything to add to the issue. Otherwise I'm closing it, because your cluster is returning an invalid response to the `_nodes` request (an unreachable address), and that is not an issue with yii2-elasticsearch component.

**Comment by Locustv2** [comment]
Hi @beowulfenator, sorry, i just resumed my work on elasticsearch today. Sorry for the late response.
I'm good with `autodetectCluster` set to `false` and just tunnelling to my servers for testing purposes.

Thanks
