### ISSUE TITLE
Pagination in ActiveDataProvider error (Result window is too)

### ISSUE THREAD

**Issue by jafaripur** [yiisoft/yii2-elasticsearch#89]
### What steps will reproduce the problem?

Paginate to last page. for example size is 10 and from 12000 document.

### What's expected?

Load the request page.
The request body is:
```json
{
   "fields":[
      "_id",
      "title",
      "date"
   ],
   "size":10,
   "from":11880,
   "query":{
      "filtered":{
         "filter":{
            "bool":{
               "must":[

               ]
            }
         }
      }
   },
   "sort":[
      {
         "date":{
            "order":"desc"
         }
      }
   ]
}
```

### What do you get instead?

Result window is too
large, from + size must be less than or equal to: [10000] but was
[11890]. See the scroll api for a more efficient way to request large
data sets. This limit can be set by changing the
[index.max_result_window] index level parameter.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | dev-master
| PHP version      | 5.6
| Operating system | Ubuntu 16.04

**Comment by beowulfenator** [comment]
I am surprised it didn't fail earler :)

[Elastic doesn't support deep pagination very well] (https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html). (See the "Deep Paging in Distributed Systems" block).

You should either prohibit going to pages that are too deep, or if you really need all those pages, use `Query::batch()` for scroll API.

**Comment by jafaripur** [comment]
I used `yii\elasticsearch\ActiveDataProvider` for populate model and show pagination. Now, what's your preferred solution for this issue!?

**Comment by beowulfenator** [comment]
Do you truly need to be able to get to the last page of search results? If so, ElasticSearch is not the right database for you. The limitation is in the architecture of ElasticSearch itself, and not in its yii2-specific implementation.

**Comment by jafaripur** [comment]
@beowulfenator Yes, I will set limit to 1000 record for each search.

**Comment by B0rner** [comment]
I have encountered the same problem. I am using ES 7 with Yii2 and ActiveDataProvider in conjunction with ListView widget. This usually works very well in Yii2. However, the behavior of at >10000 hits is not valid.
Setting ->addOptions(['track_total_hits' => 'true']) outputs the correct number of hits. Nevertheless, the ListView widget stocks on results page Number >1000 (with 10 results per page).
The pagination header of the ListView shows more hits/pages ([999][1000][1001][1002]...). But: as soon as you go, with the ListView, to a result above 10k, you get the error.

Of course, very rarely a user scrolls to the result page 1123, but if he does or if he jumps or a bot is reaching this point - the widget should work. It doesn't make sense to set the number of documents found to 10k - that confuses the users of the application. Nor does it make sense to display the correct number of hits when the widget cannot address the documents >10k. Handling big result lists -> this is exactly what pagination is used for.
