### ISSUE TITLE
Adding aggregation to queries confusion

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2-elasticsearch#90]
First of all, the docs do need some updates as there are a lot of confusions of how to use the methods available.

I am trying to do a bit of statistics on some fields as follows:

$record = Record::find()->addAgg('somename', 'avg', ['field' => 'myfield'])->where(['some conditions'])->all()

in the es debug panel, i do get the result in 'aggregations', but how do i get in my activerecord?

**Comment by samdark** [comment]
> First of all, the docs do need some updates as there are a lot of confusions of how to use the methods available.

Would be great if you'll point to exact instances which need updates. We're looking at docs too much and do not notice obvious issues often. If you'll make a pull request with the change it would be wonderful.

**Comment by samdark** [comment]
In order to get aggregations in result, use `->search()` instead of `->all()`.

**Comment by beowulfenator** [comment]
Or you can try the new ActiveDataProvider class, which has both models and aggregations.
