### ISSUE TITLE
 Elasticsearch request failed with code 500.

### ISSUE THREAD

**Issue by Aibric** [yiisoft/yii2-elasticsearch#95]
Elasticsearch request failed with code 500.

    /**
     * @return array This model's mapping
     */
    public static function mapping()
    {
        return [
            static::type() => [
                "_id" => ["path" => "id", "index" => "not_analyzed", "store" => "yes"],
                'properties' => [
                    'author_name'    => ['type' => 'string'],
                    'publisher_name' => ['type' => 'string'],
                     'created_at'     => ['type' => 'long'],
                    'updated_at'     => ['type' => 'long'],
                     'status'         => ['type' => 'long'],
                ]
            ],
        ];
    }
    /**
     * Create this model's index
     */
    public static function createIndex()
    {
        $db = static::getDb();
        $command = $db->createCommand();
        $command->createIndex(static::index(), [
            'settings' => [ /* ... */ ],
            'mappings' => static::mapping(),
            //'warmers' => [ /* ... */ ],
            //'aliases' => [ /* ... */ ],
            //'creation_date' => '...'
        ]);
    }
    Model::createIndex();

Create this model's index

Elasticsearch request failed with code 500.

Error Info:

    Array
    (
        [requestMethod] => PUT
        [requestUrl] => http://127.0.0.1:9200/esgoods
        [requestBody] => {"settings":[],"mappings":{"esgoods":{"_id":{"path":"id","index":"not_analyzed","store":"yes"},"properties":{"goods_name":{"type":"string"}}}}}
        [responseCode] => 500
        [responseHeaders] => Array
            (
                [content-type] => application/json; charset=UTF-8
                [content-length] => 227
            )
        [responseBody] => Array
            (
                [error] => Array
                    (
                        [root_cause] => Array
                            (
                                [0] => Array
                                    (
                                        [type] => class_cast_exception
                                        [reason] => java.util.ArrayList cannot be cast to java.util.Map
                                    )

                            )

                        [type] => class_cast_exception
                        [reason] => java.util.ArrayList cannot be cast to java.util.Map
                    )

                [status] => 500
            )
    )

**Comment by samdark** [comment]
How to reproduce that?

**Comment by beowulfenator** [comment]
This looks like a bug in the ES server, not in the yii2-elasticsearch component.

**Comment by samdark** [comment]
Either that or data sent isn't in valid format.

**Comment by Aibric** [comment]
Thanks @amdark and@beowulfenator Already solved  ,not in the yii2-elasticsearch component.
